// frontend-react/src/features/admin/orders/OrderList.tsx
import { Pagination } from "@mui/material";
import { ChangeEvent, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { FaRegEye } from "react-icons/fa";

import NotFound from "src/ui/NotFound";
import { getAllOrders } from "src/services/apiOrder";
import { convertToDateString, formatCurrency } from "src/utils/helpers";
import { TOrderStatus } from "src/interfaces/order";
import Loader from "src/ui/Loader";

const PER_PAGE = 10;

const getStatusClass = (status: TOrderStatus) => {
  switch (status) {
    case "Pending":
      return "pending-st";
    case "Cancelled":
      return "cancel-st";
    case "Delivered":
      return "delivered-st";
    case "Confirmed":
      return "confirmed-st";
    default:
      return "";
  }
};

export default function OrderList() {
  const [curPage, setCurPage] = useState(1);
  const [filterStatus, setFilterStatus] = useState<TOrderStatus | "">("");
  const [totalPages, setTotalPages] = useState(0);

  const start = (curPage - 1) * PER_PAGE;
  const end = curPage * PER_PAGE;

  const handleChangePage = (event: ChangeEvent<unknown>, page: number) => {
    setCurPage(page);
  };

  const {
    data: orders,
    isError,
    isLoading,
  } = useQuery({
    queryKey: ["allOrders"],
    queryFn: getAllOrders,
  });

  useEffect(() => {
    if (orders) {
      setTotalPages(
        Math.ceil(
          orders.filter((o) =>
            filterStatus ? o.status === filterStatus : true,
          ).length / PER_PAGE,
        ),
      );
    }
  }, [orders, filterStatus]);

  if (isLoading) {
    return <Loader />;
  }

  return (
    <div>
      <div className="mb-4 items-center justify-between lg:flex">
        <h1 className="mb-4 text-2xl font-semibold text-stone-800 lg:mb-0">
          Orders
        </h1>
        <select
          name="filterStatus"
          id="filterStatus"
          className="ms-8 w-[160px] cursor-pointer rounded-md border border-primary-600 px-1 py-2"
          onChange={(e) => setFilterStatus(e.target.value as TOrderStatus | "")}
        >
          <option value="">Status</option>
          <option value="Pending">Pending</option>
          <option value="Confirmed">Confirmed</option>
          <option value="Cancelled">Cancelled</option>
          <option value="Delivered">Delivered</option>
        </select>
      </div>
      {isError ||
      !orders?.filter((o) => (filterStatus ? o.status === filterStatus : true))
        .length ? (
        <NotFound message="No orders found." bigSize={false} />
      ) : (
        <div>
          <table className="w-full text-left text-gray-600">
            <thead className="bg-[#f5f5f5] text-sm">
              <tr>
                <th className="uppercase">ID</th>
                <th className="uppercase">Date</th>
                <th className="uppercase">Customer</th>
                <th className="uppercase">Status</th>
                <th className="uppercase">Payment Method</th>
                <th className="uppercase">Total</th>
                <th className="uppercase">Action</th>
              </tr>
            </thead>
            <tbody>
              {orders
                .filter((o) =>
                  filterStatus ? o.status === filterStatus : true,
                )
                .slice(start, end)
                .map((o) => (
                  <tr>
                    <td className="flex items-center">#{o.invoiceNo}</td>
                    <td>{convertToDateString(o.createdAt)}</td>
                    <td>
                      {o.customerInfo.firstName + " " + o.customerInfo.lastName}
                    </td>
                    <td>
                      <td>
                        <span
                          className={`rounded-md px-2 py-1 ${getStatusClass(o.status)}`}
                        >
                          {o.status}
                        </span>
                      </td>
                    </td>
                    <td>{o.paymentInfo.paymentMethod}</td>
                    <td>{formatCurrency(o.totalPrice)}</td>
                    <td>
                      <div className="flex items-center gap-3">
                        <Link
                          to={"/admin/orders/detail/" + o._id}
                          className="flex items-center"
                        >
                          <FaRegEye className="text-2xl text-blue-500" />
                        </Link>
                        <div className="flex items-center gap-3">
                          <input
                            type="checkbox"
                            className="h-5 w-5 cursor-pointer"
                          />
                        </div>
                      </div>
                    </td>
                  </tr>
                ))}
            </tbody>
          </table>
          <div className="float-end mt-4">
            <Pagination
              count={totalPages}
              variant="outlined"
              shape="rounded"
              page={curPage}
              onChange={handleChangePage}
            />
          </div>
        </div>
      )}
    </div>
  );
}

// frontend-angular/src/app/features/admin/order/order-list/order-list.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { MatIconModule } from '@angular/material/icon';
import { RouterLink } from '@angular/router';
import { CommonModule, DatePipe } from '@angular/common';

import { IOrder } from '../../../../core/models/order.model';
import { OrderService } from '../../../../core/services/order.service';
import { CurrencyPipe } from '../../../../core/pipes/currency.pipe';
import { PaginatorComponent } from '../../../../shared/components/paginator/paginator.component';
import { LoaderComponent } from '../../../../shared/components/loader/loader.component';
import { NotFoundComponent } from '../../../../shared/components/not-found/not-found.component';
import { ToastrService } from 'ngx-toastr';

@Component({
  selector: 'app-order-list',
  standalone: true,
  imports: [MatIconModule, RouterLink, DatePipe, CurrencyPipe, PaginatorComponent, LoaderComponent, NotFoundComponent, CommonModule],
  templateUrl: './order-list.component.html',
  styleUrl: './order-list.component.css'
})

export class OrderListComponent implements OnInit {
  filterOrders!: IOrder[];
  allOrders!: IOrder[];
  totalRecords: number = 0;
  first: number = 0;
  rows: number = 10;
  isLoading: boolean = false;

  private orderService = inject(OrderService);
  private toast = inject(ToastrService);

  ngOnInit(): void {
    this.getAllOrders();
  }

  getAllOrders(page: number = 0, limit: number = 10) {
    this.isLoading = true;
    this.orderService.getAllOrders(page, limit).subscribe({
      next: (res) => {
        this.filterOrders = res.data;
        this.allOrders = res.data;
        this.totalRecords = res.totalRecords;
        this.isLoading = false;
      },
      error: (error) => {
        if (this.filterOrders.length === 0) {
          this.isLoading = false;
        }
      }
    });
  }

  onPageChanged(event: any) {
    console.log(event);
    this.first = event.first;
    this.rows = event.rows;
    this.getAllOrders(event.page + 1, event.rows);
  }

  onSelectStatus($event: Event) {
    const target = $event.target as HTMLSelectElement;

    if (target.value) {
      this.filterOrders = this.allOrders.filter(order => order.status === target.value);
    } else {
      this.getAllOrders();
    }
  }

  onConfirmed(id: string) {
    this.orderService.updateOrder(id, { status: "Confirmed" }).subscribe({
      next: (res) => {
        this.toast.success('Order is confirmed');
        this.filterOrders = this.filterOrders.filter(order => order._id !== res.data._id);;
      }
    });
  }
}

<div class="pb-10">
    <div class="lg:flex items-center justify-between mb-4">
        <h1 class="mb-4 lg:mb-0 text-2xl font-semibold text-stone-800">Orders</h1>
        <select name="filterStatus" id="filterStatus" (change)="onSelectStatus($event)"
            class="py-2 px-1 border w-[160px] rounded-md cursor-pointer ms-8 border-primary-600">
            <option value="">Status</option>
            <option value="Pending">Pending</option>
            <option value="Confirmed">Confirmed</option>
            <option value="Cancelled">Cancelled</option>
            <option value="Delivered">Delivered</option>
        </select>
    </div>
    @if(isLoading) {
    <app-loader></app-loader>
    }
    @if(!filterOrders?.length && !isLoading) {
    <app-not-found></app-not-found>
    }
    @if(filterOrders?.length && !isLoading) {
    <div>
        <table class="w-full text-left text-gray-600">
            <thead class="bg-[#f5f5f5] text-sm">
                <tr>
                    <th class="uppercase">ID</th>
                    <th class="uppercase">Date</th>
                    <th class="uppercase">Customer</th>
                    <th class="uppercase">Status</th>
                    <th class="uppercase">Payment Method</th>
                    <th class="uppercase">Total</th>
                    <th class="uppercase">Action</th>
                </tr>
            </thead>
            <tbody>
                @for(order of filterOrders; track order._id) {
                <tr>
                    <td class="flex items-center">
                        #{{order.invoiceNo}}
                    </td>
                    <td>{{order.createdAt | date: 'dd/MM/yyyy'}}</td>
                    <td>{{order.customerInfo.firstName + ' ' + order.customerInfo.lastName}}</td>
                    <td [ngClass]="{
                        'pending-st': order.status === 'Pending',
                        'cancel-st': order.status === 'Cancelled',
                        'delivered-st': order.status === 'Delivered',
                        'confirmed-st': order.status === 'Confirmed'
                      }">
                        {{order.status}}
                    </td>
                    <td>
                        <span class="px-2 py-1 rounded-md"
                            [ngClass]="{'bg-primary-300 text-primary-600': order.paymentInfo.paymentMethod === 'Cash'}">
                            {{order.paymentInfo.paymentMethod}}
                        </span>
                    </td>
                    <td>{{order.totalPrice | currency}}</td>
                    <td>
                        <div class="flex items-center gap-3">
                            <a routerLink="order/{{order._id}}" class="flex items-center">
                                <mat-icon class="scale-110">
                                    <span class="material-symbols-outlined text-blue-500">
                                        visibility
                                    </span>
                                </mat-icon>
                            </a>
                            @if(order.status === 'Pending') {
                            <div class="flex items-center gap-3">
                                <input type="checkbox" class="w-5 h-5 cursor-pointer" (change)="onConfirmed(order._id)">
                            </div>
                            }
                        </div>
                    </td>
                </tr>
                }
            </tbody>
        </table>
        <app-paginator [totalRecords]="totalRecords" [first]="first" [rows]="rows"
            (pageChangeEvent)="onPageChanged($event)"></app-paginator>
    </div>
    }
</div>
