// frontend-angular/src/app/pages/user/checkout/checkout.component.ts
import { Component } from '@angular/core';
import { CheckoutFormComponent } from '../../../features/user/checkout/checkout-form/checkout-form.component';
import { CheckoutSummaryComponent } from '../../../features/user/checkout/checkout-summary/checkout-summary.component';

@Component({
  selector: 'app-checkout',
  standalone: true,
  imports: [CheckoutFormComponent, CheckoutSummaryComponent],
  templateUrl: './checkout.component.html',
  styleUrl: './checkout.component.css'
})

export class CheckoutComponent {

}

<section class="bg-gray-50">
    <div class="mx-auto max-w-screen-2xl px-3 sm:px-10">
        <div
            class="flex w-full flex-col px-0 py-10 md:flex-row lg:flex-row lg:py-12 xl:max-w-screen-xl 2xl:max-w-screen-2xl">
            <app-checkout-form></app-checkout-form>
            <app-checkout-summary></app-checkout-summary>
        </div>
    </div>
</section>

// frontend-react/src/features/app/checkout/index.tsx
import OrderForm from "./OrderForm";
import OrderSummary from "./OrderSummary";

export default function CheckoutFeature() {
  return (
    <section className="bg-gray-50">
      <div className="mx-auto max-w-screen-2xl px-3 sm:px-10">
        <div className="flex w-full flex-col px-0 py-10 md:flex-row lg:flex-row lg:py-12 xl:max-w-screen-xl 2xl:max-w-screen-2xl">
          <OrderForm />
          <OrderSummary />
        </div>
      </div>
    </section>
  );
}
