// frontend-react/src/ui/ProductItem.tsx
import { useDispatch } from "react-redux";
import { BsBagPlusFill } from "react-icons/bs";

import { type IProduct } from "../interfaces/IProduct";
import { PUBLIC_ENDPOINTS } from "../constants/url";
import { formatCurrency, formatDiscount } from "../utils/helpers";
import { AppDispatch } from "../store/store";
import { addItem } from "../store/cart/cartSlice";

type ProductItemProps = {
  product: IProduct;
};

export default function ProductItem({ product }: ProductItemProps) {
  const dispatch = useDispatch<AppDispatch>();

  const discount =
    ((product.orgPrice - product.price) / product.orgPrice) * 100;

  const handleAddToCart = () => {
    dispatch(
      addItem({
        id: product._id,
        image: product.images[0],
        name: product.name,
        price: product.price,
        quantity: 1,
        category: product.categoryId.name,
      }),
    );
  };

  return (
    <li>
      <div className="relative h-full overflow-hidden rounded-md bg-white px-2 py-3 shadow-sm">
        <div className="absolute left-0 top-0 z-10 rounded-full bg-gray-100 px-2 py-0 text-xs font-medium text-primary-600">
          {product.quantity > 0 ? (
            <span>
              Stock:
              <span className="pl-1 font-bold text-orange-700">
                {product.quantity}
              </span>
            </span>
          ) : (
            <span className="pl-1 font-bold text-orange-700">Stock Out</span>
          )}
        </div>
        {discount > 0 ? (
          <div className="text-dark absolute right-0 top-0 z-10 rounded bg-orange-500 px-2 py-1 text-xs font-medium text-white">
            {formatDiscount(discount)}% Off
          </div>
        ) : (
          ""
        )}
        <div className="flex cursor-pointer items-center justify-center overflow-hidden px-2 py-3 transition-transform duration-300 ease-in-out hover:scale-105 lg:px-4 lg:py-5">
          <img
            src={`${PUBLIC_ENDPOINTS.IMAGE_PRODUCTS}/${product.images[0]}`}
            alt={product.name}
            className="h-40 w-40 object-cover"
          />
        </div>
        <div className="px-2 pb-2 text-start">
          <h3 className="mb-2">{product.name}</h3>
          <div className="flex items-center justify-between">
            <div>
              <span className="block text-lg font-semibold">
                {formatCurrency(product.price)}
              </span>
              <del className="text-base text-gray-400">
                {product.orgPrice > product.price
                  ? formatCurrency(product.orgPrice)
                  : ""}
              </del>
            </div>
            <span
              className="cursor-pointer rounded-md border border-gray-200 p-2 text-primary-600 hover:bg-primary-600 hover:text-white"
              onClick={handleAddToCart}
            >
              <BsBagPlusFill className="text-lg text-inherit" />
            </span>
          </div>
        </div>
      </div>
    </li>
  );
}

// frontend-angular/src/app/shared/components/product-item/product-item.component.ts
import { Component, Input } from '@angular/core';
import { MatIconModule } from '@angular/material/icon';
import { PUBLIC_ENDPOINTS } from '../../../core/constants/urls';
import { IProduct } from '../../../core/models/products.model';
import { CartService } from '../../../core/services/cart.service';
import { CurrencyPipe } from '../../../core/pipes/currency.pipe';

@Component({
  selector: 'app-product-item',
  standalone: true,
  imports: [MatIconModule, CurrencyPipe],
  templateUrl: './product-item.component.html',
  styleUrl: './product-item.component.css'
})

export class ProductItemComponent {
  @Input() product!: IProduct;
  imageUrl = PUBLIC_ENDPOINTS.IMAGE_PRODUCTS;

  constructor(private cartService: CartService) { }

  onAddToCart(product: IProduct) {
    const item = {
      id: product._id,
      image: product.images[0],
      name: product.name,
      quantity: 1,
      price: product.price,
      category: product.categoryId.name!,
    };
    this.cartService.addToCart(item);
  }
}

<li>
    <div class="relative overflow-hidden rounded-md bg-white px-2 py-3 shadow-sm">
        <div class="absolute left-0 top-0 z-10 rounded-full bg-gray-100 px-2 py-0 text-xs font-medium text-primary-600">
            @if(product.quantity > 0) {
            <span>
                Stock:
                <span class="pl-1 font-bold text-orange-700">
                    {{product.quantity}}
                </span>
            </span>
            } @else {
            <span class="pl-1 font-bold text-orange-700">
                Stock out
            </span>
            }
        </div>
        @if(product.orgPrice > product.price) {
        <div
            class="text-dark absolute right-0 top-0 z-10 rounded bg-orange-500 px-2 py-1 text-xs font-medium text-white">
            {{((product.orgPrice - product.price) / product.orgPrice * 100).toFixed(1)}} Off
        </div>
        }
        <div
            class="flex cursor-pointer items-center justify-center overflow-hidden px-2 py-3 transition-transform duration-300 ease-in-out hover:scale-105 lg:px-4 lg:py-5">
            <img src="{{imageUrl}}/{{product.images[0]}}" alt={{product.name}} class="h-40 w-40 object-cover" />
        </div>
        <div class="px-2 pb-2 text-start">
            <h3 class="mb-2">{{product.name}}</h3>
            <div class="flex items-center justify-between">
                <div>
                    <span class="block text-lg font-semibold">
                        {{product.price | currency}}
                    </span>
                    <del class="text-base text-gray-400">
                        ${{product.orgPrice | currency}}
                    </del>
                </div>
                <span
                    class="flex items-center cursor-pointer rounded-md border border-gray-200 p-2 text-primary-600 hover:bg-primary-600 hover:text-white"
                    (click)="onAddToCart(product)">
                    <mat-icon>
                        <span class="material-symbols-outlined">
                            add_shopping_cart
                        </span>
                    </mat-icon>
                </span>
            </div>
        </div>
    </div>
</li>
