// frontend-react/src/layouts/admin/Footer.tsx
export default function Footer() {
  return (
    <footer className="absolute bottom-0 flex h-16 w-full flex-auto items-center !bg-white px-4 sm:px-6 md:px-8">
      <div className="flex w-full flex-auto items-center justify-between">
        <span>
          Copyright © 2024 <span className="font-semibold">ngChinh</span> All
          rights reserved.
        </span>
        <div className="">
          <a className="text-gray" href="/#">
            Term &amp; Conditions
          </a>
          <span className="text-muted mx-2"> | </span>
          <a className="text-gray" href="/#">
            Privacy &amp; Policy
          </a>
        </div>
      </div>
    </footer>
  );
}

// frontend-angular/src/app/shared/layouts/admin/footer/footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-admin-footer',
  standalone: true,
  imports: [],
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.css'
})
export class FooterComponent {

}

<footer class="absolute bottom-0 flex h-16 flex-auto items-center !bg-white px-4 sm:px-6 md:px-8">
    <div class="flex w-full flex-auto items-center justify-between">
        <span>
            Copyright © 2024 <span class="font-semibold">Elstar</span>
            All rights reserved.
        </span>
        <div class="">
            <a class="text-gray" href="/#">
                Term &amp; Conditions
            </a>
            <span class="text-muted mx-2"> | </span>
            <a class="text-gray" href="/#">
                Privacy &amp; Policy
            </a>
        </div>
    </div>
</footer>
