// frontend-angular/src/app/features/user/user-detail/change-password/change-password.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { FormBuilder, FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ToastrService } from 'ngx-toastr';

import { AuthService } from '../../../../core/services/auth.service';

@Component({
  selector: 'app-change-password',
  standalone: true,
  imports: [ReactiveFormsModule],
  templateUrl: './change-password.component.html',
  styleUrl: './change-password.component.css'
})

export class ChangePasswordComponent implements OnInit {
  form!: FormGroup;
  userId!: string;

  private authService = inject(AuthService);
  private formBuilder = inject(FormBuilder);
  private toast = inject(ToastrService);

  ngOnInit(): void {
    this.form = this.formBuilder.group({
      email: new FormControl('', [Validators.required]),
      currentPassword: new FormControl('', [Validators.required, Validators.minLength(6)]),
      newPassword: new FormControl('', [Validators.required, Validators.minLength(6)]),
    });
    this.form.controls['email'].disable();
    this.authService.userProfile$.subscribe(data => {
      if (data) {
        this.userId = data._id;
        this.form.patchValue({ email: data.email });
      }
    });
  }

  onSubmit() {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
    } else {
      this.form.value.newPassword;
      this.authService.changePassword(this.userId, this.form.value).subscribe({
        next: (res) => {
          console.log(res);
          this.toast.success("Your password is updated");
        },
        error: (err) => {
          if (err?.status === 403) {
            this.toast.error("Your current password is incorrect");
          }
          console.error(err);
        }
      });
    }
  }
}

<h2 class="text-xl text-gray-600 font-semibold mb-5">Change Password</h2>
<form [formGroup]="form" (submit)="onSubmit()">
    <div class="w-full mt-5">
        <label class="mb-2 block text-sm font-medium leading-none text-gray-500">
            Email
        </label>
        <div>
            <div class="relative">
                <input type="text" placeholder="Your email"
                    class="text-input placeholder-body h-11 min-h-12 w-full appearance-none rounded-md border border-gray-200 bg-white py-2 pl-5 text-sm opacity-75 transition duration-200 ease-in-out focus:border-primary-600 focus:outline-none focus:ring-0 md:h-12"
                    formControlName="email" [disabled]="true" />
            </div>
            @if(form.get('email')?.hasError('required') && form.get('email')?.touched) {
            <small class="text-red-600 text-[15px] pt-1 inline-block">(*) Email is required</small>
            }
        </div>
    </div>
    <div class="w-full mt-5">
        <label class="mb-2 block text-sm font-medium leading-none text-gray-500">
            Current Password
        </label>
        <div>
            <div class="relative">
                <input type="text" placeholder="Your current password"
                    class="text-input placeholder-body h-11 min-h-12 w-full appearance-none rounded-md border border-gray-200 bg-white py-2 pl-5 text-sm opacity-75 transition duration-200 ease-in-out focus:border-primary-600 focus:outline-none focus:ring-0 md:h-12"
                    formControlName="currentPassword" />
            </div>
            @if(form.get('currentPassword')?.touched) {
            @if(form.get('currentPassword')?.hasError('required')) {
            <small class="text-red-600 text-[15px] pt-1 inline-block">(*) Current password is required</small>
            }@else if(form.get('currentPassword')?.hasError('minlength')){
            <small class="text-red-600 text-[15px] pt-1 inline-block">(*) Current password must be at least 6
                characters</small>
            }
            }
        </div>
    </div>
    <div class="w-full mt-5">
        <label class="mb-2 block text-sm font-medium leading-none text-gray-500">
            New Password
        </label>
        <div>
            <div class="relative">
                <input type="text" placeholder="Your new password"
                    class="text-input placeholder-body h-11 min-h-12 w-full appearance-none rounded-md border border-gray-200 bg-white py-2 pl-5 text-sm opacity-75 transition duration-200 ease-in-out focus:border-primary-600 focus:outline-none focus:ring-0 md:h-12"
                    formControlName="newPassword" />
            </div>
            @if(form.get('newPassword')?.touched) {
            @if(form.get('newPassword')?.hasError('required')) {
            <small class="text-red-600 text-[15px] pt-1 inline-block">(*) New password is required</small>
            }@else if(form.get('newPassword')?.hasError('minlength')){
            <small class="text-red-600 text-[15px] pt-1 inline-block">(*) New password must be at least 6
                characters</small>
            }
            }
        </div>
    </div>
    <div class="mt-5 text-right">
        <button
            class="md:text-sm leading-5 cursor-pointer transition ease-in-out duration-300 font-medium text-center justify-center border-0 border-transparent rounded-md placeholder-white focus-visible:outline-none focus:outline-none bg-primary-600 text-white px-5 md:px-6 lg:px-8 py-2 md:py-3 lg:py-3 hover:text-white hover:bg-primary-700 h-12 mt-1 text-sm lg:text-sm w-full sm:w-auto">Update
            Password</button>
    </div>
</form>

// frontend-react/src/features/app/user/ChangePassword.tsx
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { useSelector } from "react-redux";

import { IChangePassword } from "src/interfaces/auth";
import { RootState } from "src/store/store";
import { changePasswordSchema } from "src/zods/auth";
import Input from "src/ui/Input";
import Loader from "src/ui/Loader";
import { toastUI } from "src/utils/toast";
import { useMutation } from "@tanstack/react-query";
import { AxiosError } from "axios";
import { changePassword } from "src/services/apiAuth";

export default function ChangePassword() {
  const currentUser = useSelector((state: RootState) => state.auth.user);

  const {
    register,
    handleSubmit,
    formState: { isSubmitting, errors },
  } = useForm<IChangePassword>({
    resolver: zodResolver(changePasswordSchema),
    defaultValues: {
      email: currentUser?.email,
    },
  });

  const { mutate: changePasswordMutation, isPending } = useMutation<
    unknown,
    // eslint-disable-next-line
    AxiosError<any, any>,
    IChangePassword
  >({
    mutationFn: (data) => changePassword(data),
    onSuccess: (res) => {
      console.log(res);
      toastUI("Your password updated successfully", "success");
    },
    onError: (err) => {
      toastUI(err.response?.data.error, "error");
    },
  });

  if (!currentUser) {
    toastUI("Something went wrong! No user found.", "error");
    return;
  }

  const onSubmit = (data: IChangePassword) => {
    changePasswordMutation(data);
  };

  return (
    <>
      {isSubmitting ? (
        <Loader />
      ) : (
        <>
          <h2 className="mb-5 text-xl font-semibold text-gray-600">
            Change Password
          </h2>
          <form onSubmit={handleSubmit(onSubmit)}>
            <div className="mt-5">
              <Input
                disabled={true}
                register={register}
                errors={errors}
                label="Email"
                name="email"
                placeholder="Your email"
                type="text"
              />
            </div>
            <div className="mt-5">
              <Input
                register={register}
                errors={errors}
                label="Current Password"
                name="currentPassword"
                placeholder="Your current password"
                type="password"
              />
            </div>
            <div className="mt-5">
              <Input
                register={register}
                errors={errors}
                label="New Password"
                name="newPassword"
                placeholder="Your new password"
                type="password"
              />
            </div>
            <div className="mt-5 text-right">
              <button className="mt-1 h-12 w-full cursor-pointer justify-center rounded-md border-0 border-transparent bg-primary-600 px-5 py-2 text-center text-sm font-medium leading-5 text-white placeholder-white transition duration-300 ease-in-out hover:bg-primary-700 hover:text-white focus:outline-none focus-visible:outline-none sm:w-auto md:px-6 md:py-3 md:text-sm lg:px-8 lg:py-3 lg:text-sm">
                Update Password
              </button>
            </div>
          </form>
        </>
      )}
    </>
  );
}
