// frontend-angular/src/app/features/user/user-detail/order-detail/order-detail.component.ts
import { Component, OnDestroy, OnInit, inject } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Subscription } from 'rxjs';

import { OrderService } from '../../../../core/services/order.service';
import { IOrder } from '../../../../core/models/order.model';
import { CurrencyPipe } from '../../../../core/pipes/currency.pipe';
import { DatePipe } from '@angular/common';

@Component({
  selector: 'app-order-detail',
  standalone: true,
  imports: [CurrencyPipe, DatePipe],
  templateUrl: './order-detail.component.html',
  styleUrl: './order-detail.component.css'
})

export class OrderDetailComponent implements OnInit, OnDestroy {
  routeSub!: Subscription;
  order!: IOrder;

  actRouter = inject(ActivatedRoute);
  orderService = inject(OrderService);

  ngOnInit(): void {
    this.routeSub = this.actRouter.params.subscribe(params => {
      this.orderService.getOrderById(params['id']).subscribe({
        next: (res) => {
          this.order = res.data;
        }
      });
    });
  }

  ngOnDestroy(): void {
    this.routeSub.unsubscribe();
  }
}

<div class="bg-gray-50">
    <div class="max-w-screen-2xl mx-auto py-10 px-3 sm:px-6">
        <div class="bg-emerald-100 rounded-md mb-5 px-4 py-3"><label>Thank You <span
                    class="font-bold text-emerald-600">{{order.customerInfo.firstName + ' ' +
                    order.customerInfo.lastName}},</span> Your order have been received ! Please check
                your email in order to download the invoice.</label>
        </div>
        <div class="bg-white rounded-lg shadow-sm">
            <div>
                <div class="bg-indigo-50 p-8 rounded-t-xl">
                    <div
                        class="flex lg:flex-row md:flex-row flex-col lg:items-center justify-between pb-4 border-b border-gray-50">
                        <div>
                            <h1 class="font-bold text-2xl uppercase">Invoice</h1>
                            <h6 class="text-gray-700">Status : <span class="text-orange-500">{{order.status}}</span>
                            </h6>
                        </div>
                        <div class="lg:text-right text-left">
                            <h2 class="text-lg font-semibold mt-4 lg:mt-0 md:mt-0"><a href="/"><img alt="logo"
                                        loading="lazy" width="110" height="40" decoding="async" data-nimg="1"
                                        src="/logo/logo-color.svg" style="color: transparent;"></a></h2>
                            <p class="text-sm text-gray-500">59 Station Rd, Purls Bridge, United Kingdom</p>
                        </div>
                    </div>
                    <div class="flex lg:flex-row md:flex-row flex-col justify-between pt-4">
                        <div class="mb-3 md:mb-0 lg:mb-0 flex flex-col"><span
                                class="font-bold text-sm uppercase text-gray-600 block">Date</span><span
                                class="text-sm text-gray-500 block"><span>{{order.createdAt | date:
                                    'dd/MM/yyyy'}}</span></span></div>
                        <div class="mb-3 md:mb-0 lg:mb-0 flex flex-col"><span
                                class="font-bold text-sm uppercase text-gray-600 block">Invoice
                                No.</span><span class="text-sm text-gray-500 block">#{{order.invoiceNo}}</span></div>
                        <div class="flex flex-col lg:text-right text-left"><span
                                class="font-bold text-sm uppercase text-gray-600 block">Invoice
                                To.</span><span class="text-sm text-gray-500 block">{{order.customerInfo.firstName}}
                                {{order.customerInfo.lastName}}
                                <br>{{order.customerInfo.email}}
                                <span
                                    class="ml-2">{{order.customerInfo.phone}}</span><br>{{order.shippingInfo.address}},
                                {{order.shippingInfo.city}}, {{order.shippingInfo.country}}<br>
                            </span></div>
                    </div>
                </div>
                <div class="s">
                    <div class="overflow-hidden lg:overflow-visible px-8 my-10">
                        <div class="-my-2 overflow-x-auto">
                            <table class="table-auto min-w-full border border-gray-100 divide-y divide-gray-200">
                                <thead class="bg-gray-50">
                                    <tr class="text-xs bg-gray-100">
                                        <th scope="col"
                                            class="font-semibold px-6 py-2 text-gray-700 uppercase tracking-wider text-left">
                                            Sr.</th>
                                        <th scope="col"
                                            class="font-semibold px-6 py-2 text-gray-700 uppercase tracking-wider text-left">
                                            Product Name</th>
                                        <th scope="col"
                                            class="font-semibold px-6 py-2 text-gray-700 uppercase tracking-wider text-center">
                                            Quantity</th>
                                        <th scope="col"
                                            class="font-semibold px-6 py-2 text-gray-700 uppercase tracking-wider text-center">
                                            Item Price</th>
                                        <th scope="col"
                                            class="font-semibold px-6 py-2 text-gray-700 uppercase tracking-wider text-right">
                                            Amount</th>
                                    </tr>
                                </thead>
                                <tbody class="bg-white divide-y divide-gray-100 text-serif text-sm">
                                    @for(item of order.orderItems; track item.product; let index = $index) {
                                    <tr>
                                        <th class="px-6 py-1 whitespace-nowrap font-normal text-gray-500 text-left">
                                            {{index + 1}}
                                        </th>
                                        <td class="px-6 py-1 whitespace-nowrap font-normal text-gray-500">
                                            {{item.product.name}}</td>
                                        <td class="px-6 py-1 whitespace-nowrap font-bold text-center">{{item.quantity}}
                                        </td>
                                        <td class="px-6 py-1 whitespace-nowrap font-bold text-center font-DejaVu">
                                            {{item.product.price | currency}}</td>
                                        <td
                                            class="px-6 py-1 whitespace-nowrap text-right font-bold font-DejaVu k-grid text-red-500">
                                            {{(item.quantity * item.product.price) | currency}}</td>
                                    </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="border-t border-b border-gray-100 p-10 bg-emerald-50">
                    <div class="flex lg:flex-row md:flex-row flex-col justify-between pt-4">
                        <div class="mb-3 md:mb-0 lg:mb-0  flex flex-col sm:flex-wrap"><span
                                class="mb-1 font-bold text-sm uppercase text-gray-600 block">Payment
                                Method</span><span class="text-sm text-gray-500 font-semibold block">Cash</span></div>
                        <div class="mb-3 md:mb-0 lg:mb-0  flex flex-col sm:flex-wrap"><span
                                class="mb-1 font-bold text-sm uppercase text-gray-600 block">Shipping
                                Cost</span><span
                                class="text-sm text-gray-500 font-semibold block">{{order.shippingInfo.cost! |
                                currency}}</span></div>
                        <div class="mb-3 md:mb-0 lg:mb-0  flex flex-col sm:flex-wrap"><span
                                class="mb-1 font-bold text-sm uppercase text-gray-600 block">Discount</span><span
                                class="text-sm text-gray-500 font-semibold block">€0.00</span></div>
                        <div class="flex flex-col sm:flex-wrap"><span
                                class="mb-1 font-bold text-sm uppercase text-gray-600 block">Total
                                Amount</span><span class="text-2xl font-bold text-red-500 block">{{order.totalPrice |
                                currency}}</span></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

// frontend-react/src/features/app/user/OrderDetail.tsx
import { useQuery } from "@tanstack/react-query";
import { useParams } from "react-router-dom";

import { getOrdersById } from "src/services/apiOrder";
import Loader from "src/ui/Loader";
import NotFound from "src/ui/NotFound";
import { convertToDateString, formatCurrency } from "src/utils/helpers";

import logo from "../../../assets/logo-shop.svg";

export default function OrderDetail() {
  const { id } = useParams();

  const {
    data: order,
    isPending,
    isError,
  } = useQuery({
    queryKey: ["orderDetail", id],
    queryFn: () => getOrdersById(id!),
  });

  if (isPending) {
    return <Loader />;
  }

  if (!order || isError) {
    return <NotFound message="No order found" bigSize={false} />;
  }

  return (
    <div className="bg-gray-50">
      <div className="mx-auto max-w-screen-2xl px-3 py-10 sm:px-6">
        <div className="mb-5 rounded-md bg-emerald-100 px-4 py-3">
          <label>
            Thank You{" "}
            <span className="font-bold text-emerald-600">
              {order.customerInfo.firstName + " " + order.customerInfo.lastName}
              ,{" "}
            </span>{" "}
            Your order have been received ! Please check your email in order to
            download the invoice.
          </label>
        </div>
        <div className="rounded-lg bg-white shadow-sm">
          <div>
            <div className="rounded-t-xl bg-indigo-50 p-8">
              <div className="flex flex-col justify-between border-b border-gray-50 pb-4 md:flex-row lg:flex-row lg:items-center">
                <div>
                  <h1 className="text-2xl font-bold uppercase">Invoice</h1>
                  <h6 className="text-gray-700">
                    Status :{" "}
                    <span className="text-orange-500">{order.status}</span>
                  </h6>
                </div>
                <div className="text-left lg:text-right">
                  <h2 className="mb-2 mt-4 text-lg font-semibold md:mt-0 lg:mt-0">
                    <a href="/">
                      <img
                        alt="logo"
                        loading="lazy"
                        width="110"
                        height="40"
                        decoding="async"
                        data-nimg="1"
                        src={logo}
                      />
                    </a>
                  </h2>
                  <p className="text-sm text-gray-500">
                    59 Station Rd, Purls Bridge, United Kingdom
                  </p>
                </div>
              </div>
              <div className="flex flex-col justify-between pt-4 md:flex-row lg:flex-row">
                <div className="mb-3 flex flex-col md:mb-0 lg:mb-0">
                  <span className="block text-sm font-bold uppercase text-gray-600">
                    Date
                  </span>
                  <span className="block text-sm text-gray-500">
                    <span>{convertToDateString(order.createdAt)}</span>
                  </span>
                </div>
                <div className="mb-3 flex flex-col md:mb-0 lg:mb-0">
                  <span className="block text-sm font-bold uppercase text-gray-600">
                    Invoice No.
                  </span>
                  <span className="block text-sm text-gray-500">
                    #{order.invoiceNo}
                  </span>
                </div>
                <div className="flex flex-col text-left lg:text-right">
                  <span className="block text-sm font-bold uppercase text-gray-600">
                    Invoice To.
                  </span>
                  <span className="block text-sm text-gray-500">
                    {order.customerInfo.firstName}
                    {order.customerInfo.lastName}
                    <br />
                    {order.customerInfo.email}
                    <span className="ml-2">{order.customerInfo.phone}</span>
                    <br />
                    {order.shippingInfo.address},{order.shippingInfo.city},{" "}
                    {order.shippingInfo.country}
                    <br />
                  </span>
                </div>
              </div>
            </div>
            <div className="s">
              <div className="my-10 overflow-hidden px-8 lg:overflow-visible">
                <div className="-my-2 overflow-x-auto">
                  <table className="min-w-full table-auto divide-y divide-gray-200 border border-gray-100">
                    <thead className="bg-gray-50">
                      <tr className="bg-gray-100 text-xs">
                        <th
                          scope="col"
                          className="px-6 py-2 text-left font-semibold uppercase tracking-wider text-gray-700"
                        >
                          Sr.
                        </th>
                        <th
                          scope="col"
                          className="px-6 py-2 text-left font-semibold uppercase tracking-wider text-gray-700"
                        >
                          Product Name
                        </th>
                        <th
                          scope="col"
                          className="px-6 py-2 text-center font-semibold uppercase tracking-wider text-gray-700"
                        >
                          Quantity
                        </th>
                        <th
                          scope="col"
                          className="px-6 py-2 text-center font-semibold uppercase tracking-wider text-gray-700"
                        >
                          Item Price
                        </th>
                        <th
                          scope="col"
                          className="px-6 py-2 text-right font-semibold uppercase tracking-wider text-gray-700"
                        >
                          Amount
                        </th>
                      </tr>
                    </thead>
                    <tbody className="text-serif divide-y divide-gray-100 bg-white text-sm">
                      {order.orderItems.map((item, index) => (
                        <tr>
                          <th className="whitespace-nowrap px-6 py-1 text-left font-normal text-gray-500">
                            {index + 1}
                          </th>
                          <td className="whitespace-nowrap px-6 py-1 font-normal text-gray-500">
                            {item.product.name}
                          </td>
                          <td className="whitespace-nowrap px-6 py-1 text-center font-bold">
                            {item.quantity}
                          </td>
                          <td className="font-DejaVu whitespace-nowrap px-6 py-1 text-center font-bold">
                            {formatCurrency(item.product.price)}
                          </td>
                          <td className="font-DejaVu k-grid whitespace-nowrap px-6 py-1 text-right font-bold text-red-500">
                            {formatCurrency(item.quantity * item.product.price)}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
            <div className="border-b border-t border-gray-100 bg-emerald-50 p-10">
              <div className="flex flex-col justify-between pt-4 md:flex-row lg:flex-row">
                <div className="mb-3 flex flex-col  sm:flex-wrap md:mb-0 lg:mb-0">
                  <span className="mb-1 block text-sm font-bold uppercase text-gray-600">
                    Payment Method
                  </span>
                  <span className="block text-sm font-semibold text-gray-500">
                    Cash
                  </span>
                </div>
                <div className="mb-3 flex flex-col  sm:flex-wrap md:mb-0 lg:mb-0">
                  <span className="mb-1 block text-sm font-bold uppercase text-gray-600">
                    Shipping Cost
                  </span>
                  <span className="block text-sm font-semibold text-gray-500">
                    {formatCurrency(order.shippingInfo.cost!)}
                  </span>
                </div>
                <div className="mb-3 flex flex-col  sm:flex-wrap md:mb-0 lg:mb-0">
                  <span className="mb-1 block text-sm font-bold uppercase text-gray-600">
                    Discount
                  </span>
                  <span className="block text-sm font-semibold text-gray-500">
                    €0.00
                  </span>
                </div>
                <div className="flex flex-col sm:flex-wrap">
                  <span className="mb-1 block text-sm font-bold uppercase text-gray-600">
                    Total Price
                  </span>
                  <span className="block text-2xl font-bold text-red-500">
                    {formatCurrency(order.totalPrice)}
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
