// frontend-react/src/pages/admin/Dashboard.tsx
import { useQuery } from "@tanstack/react-query";
import { GiKiwiFruit } from "react-icons/gi";
import { IoBagCheckOutline } from "react-icons/io5";
import { TfiMoney } from "react-icons/tfi";
import { Link } from "react-router-dom";
import { PUBLIC_ENDPOINTS } from "src/constants/url";

import { getAllOrders, getBestSelling } from "src/services/apiOrder";
import { getAllProducts } from "src/services/apiProducts";
import Loader from "src/ui/Loader";
import { convertToDateString, formatCurrency } from "src/utils/helpers";

export default function Dashboard() {
  const {
    data: orders,
    error: orderError,
    isLoading: orderPending,
  } = useQuery({
    queryKey: ["allOrders"],
    queryFn: getAllOrders,
  });

  const {
    data: products,
    error: productError,
    isPending: productPending,
  } = useQuery({
    queryKey: ["allProducts"],
    queryFn: getAllProducts,
  });

  const {
    data: bestSelling,
    error: bestSellingError,
    isPending: bestSellingPending,
  } = useQuery({
    queryKey: ["bestSelling"],
    queryFn: getBestSelling,
  });

  if (productPending || bestSellingPending || orderPending) {
    return <Loader />;
  }

  const revenue = orders?.reduce((total, cur) => (total += cur.totalPrice), 0);

  return (
    <div className="flex h-full flex-col gap-4 pb-20">
      <div className="mb-4 items-center justify-between gap-3 lg:flex">
        <div className="mb-4 lg:mb-0">
          <h3 className="text-2xl font-semibold">Sales Overview</h3>
          <p>View your current sales &amp; summary</p>
        </div>
        <div className="flex flex-col gap-3 lg:flex-row lg:items-center"></div>
      </div>
      <div className="grid grid-cols-1 gap-4 lg:grid-cols-3">
        <div
          className="rounded-lg border-2 border-primary-500 p-5 transition duration-150 ease-linear hover:border-orange-500"
          role="presentation"
        >
          <div className="card-body">
            <h6 className="mb-4 text-lg font-semibold">Revenue</h6>
            <div className="flex items-center justify-between">
              <div>
                <h3 className="mb-2 text-2xl font-bold">
                  <span>{formatCurrency(orderError ? 0 : revenue || 0)}</span>
                </h3>
                <p>
                  Latest update{" "}
                  <span className="font-semibold">
                    {convertToDateString(new Date().toISOString())}
                  </span>
                </p>
              </div>
              <div className="scale-[200%]">
                <TfiMoney className="text-3xl text-gray-500" />
              </div>
            </div>
          </div>
        </div>
        <div
          className="rounded-lg border-2 border-primary-500 p-5 transition duration-150 ease-linear hover:border-orange-500"
          role="presentation"
        >
          <div className="card-body">
            <h6 className="mb-4 text-lg font-semibold">Orders</h6>
            <div className="flex items-center justify-between">
              <div>
                <h3 className="mb-2 text-2xl font-bold">
                  <span>{orderError ? 0 : orders?.length || 0}</span>
                </h3>
                <p>
                  Latest update{" "}
                  <span className="font-semibold">
                    {convertToDateString(new Date().toISOString())}
                  </span>
                </p>
              </div>
              <div className="scale-[200%]">
                <IoBagCheckOutline className="text-3xl text-gray-500" />
              </div>
            </div>
          </div>
        </div>
        <div
          className="rounded-lg border-2 border-primary-500 p-5 transition duration-150 ease-linear hover:border-orange-500"
          role="presentation"
        >
          <div className="card-body">
            <h6 className="mb-4 text-lg font-semibold">Products</h6>
            <div className="flex items-center justify-between">
              <div>
                <h3 className="mb-2 text-2xl font-bold">
                  <span>{productError ? 0 : products?.length || 0}</span>
                </h3>
                <p>
                  Latest update{" "}
                  <span className="font-semibold">
                    {convertToDateString(new Date().toISOString())}
                  </span>
                </p>
              </div>
              <div className="scale-[200%]">
                <GiKiwiFruit className="text-3xl text-gray-500" />
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="grid grid-cols-1 gap-4 lg:grid-cols-3">
        <div className="card card-border lg:col-span-2" role="presentation">
          <div className="rounded-lg border-2 border-primary-500 p-5 transition duration-150 ease-linear hover:border-orange-500">
            <div className="mb-6 flex items-center justify-between">
              <h4 className="text-xl font-bold">Latest Orders</h4>
              <Link
                to="/admin/orders"
                className="rounded-lg border border-gray-300 px-3 py-2 font-medium transition-all hover:bg-gray-50"
              >
                View Orders
              </Link>
            </div>
            <div className="w-full">
              {orderError || !orders?.length ? (
                "No order found."
              ) : (
                <table className="w-full">
                  <thead className="bg-[#f5f5f5]">
                    <tr>
                      <th>Order</th>
                      <th>Status</th>
                      <th>Date</th>
                      <th>Customer</th>
                      <th>Summary</th>
                    </tr>
                  </thead>
                  <tbody>
                    {orders
                      ?.sort(
                        (a, b) =>
                          new Date(b.createdAt).getTime() -
                          new Date(a.createdAt).getTime(),
                      )
                      .slice(0, 10)
                      .map((o) => (
                        <tr key={o._id}>
                          <td>
                            <span className="cursor-pointer select-none font-semibold hover:text-indigo-600">
                              #{o.invoiceNo}
                            </span>
                          </td>
                          <td>
                            <div className="flex items-center">
                              {o.paymentInfo.isPaid ? (
                                <>
                                  <span className="badge-dot bg-primary-600"></span>
                                  <span className="ml-2 font-semibold capitalize text-primary-600 rtl:mr-2">
                                    Paid
                                  </span>
                                </>
                              ) : (
                                <>
                                  <span className="badge-dot bg-orange-500"></span>
                                  <span className="ml-2 font-semibold capitalize text-orange-500 rtl:mr-2">
                                    Pending
                                  </span>
                                </>
                              )}
                            </div>
                          </td>
                          <td>
                            <span>{convertToDateString(o.createdAt)}</span>
                          </td>
                          <td>{o.customerInfo.firstName}</td>
                          <td>
                            <span>{formatCurrency(o.totalPrice)}</span>
                          </td>
                        </tr>
                      ))}
                  </tbody>
                </table>
              )}
            </div>
          </div>
        </div>
        <div
          className="rounded-lg border-2 border-primary-500 p-5 transition duration-150 ease-linear hover:border-orange-500"
          role="presentation"
        >
          <div className="card-body">
            <div className="mb-4 flex items-center justify-between">
              <h4 className="text-xl font-bold">Top Selling</h4>
              <Link
                to="/admin/products"
                className="rounded-lg border border-gray-300 px-3 py-2 font-medium transition-all hover:bg-gray-50"
              >
                View Products
              </Link>
            </div>
            <div className="overflow-x-auto">
              {!bestSelling?.length || bestSellingError ? (
                "No products found."
              ) : (
                <table className="w-full">
                  <thead className="bg-[#f5f5f5]">
                    <tr>
                      <th>Product</th>
                      <th>Sold</th>
                    </tr>
                  </thead>
                  <tbody>
                    {bestSelling?.map((bsl) => (
                      <tr key={bsl._id}>
                        <td>
                          <div className="flex items-center gap-2">
                            <span className="avatar avatar-rounded avatar-md w-[100px]">
                              <img
                                src={
                                  PUBLIC_ENDPOINTS.IMAGE_PRODUCTS +
                                  "/" +
                                  bsl.productDetails.images[0]
                                }
                                className="avatar-img avatar-rounded pe-4"
                                loading="lazy"
                              />
                            </span>
                            <span className="text-lg font-semibold text-gray-500">
                              {bsl.productDetails.name}
                            </span>
                          </div>
                        </td>
                        <td>{bsl.totalQuantity}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// frontend-angular/src/app/pages/admin/dashboard/dashboard.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { MatIconModule } from '@angular/material/icon';

import { IBestSelling, IOrder } from '../../../core/models/order.model';
import { IProduct } from '../../../core/models/products.model';
import { OrderService } from '../../../core/services/order.service';
import { ProductsService } from '../../../core/services/products.service';
import { CurrencyPipe } from '../../../core/pipes/currency.pipe';
import { DatePipe } from '@angular/common';
import { RouterLink } from '@angular/router';
import { PUBLIC_ENDPOINTS } from '../../../core/constants/urls';

@Component({
  selector: 'app-admin-dashboard',
  standalone: true,
  imports: [MatIconModule, CurrencyPipe, DatePipe, RouterLink],
  templateUrl: './dashboard.component.html',
  styleUrl: './dashboard.component.css'
})

export class DashboardComponent implements OnInit {
  orders!: IOrder[];
  revenue!: number;
  products!: IProduct[];
  bestSelling!: IBestSelling[];
  currentDate = Date.now();
  productUrlImg = PUBLIC_ENDPOINTS.IMAGE_PRODUCTS;

  orderService = inject(OrderService);
  productService = inject(ProductsService);

  ngOnInit(): void {
    this.getAllOrders();
    this.getBestSelling();
    this.getAllProducts();
  }

  getAllOrders() {
    this.orderService.getAllOrders().subscribe({
      next: (res) => {
        this.orders = res.data.sort((a, b) =>
          new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
        );
        this.revenue = res.data.reduce((acc, cur) => acc + cur.totalPrice, 0);
      }
    });
  }

  getAllProducts() {
    this.productService.getAllProducts().subscribe({
      next: (res) => {
        this.products = res.data;
      }
    });
  }

  getBestSelling() {
    this.orderService.getBestSelling().subscribe({
      next: (res) => {
        this.bestSelling = res.data;
      }
    });
  }

}

<div class="flex flex-col gap-4 h-full pb-20">
    <div class="lg:flex items-center justify-between mb-4 gap-3">
        <div class="mb-4 lg:mb-0">
            <h3 class="text-2xl font-semibold">Sales Overview</h3>
            <p>View your current sales &amp; summary</p>
        </div>
        <div class="flex flex-col lg:flex-row lg:items-center gap-3">
        </div>
    </div>
    <div class="grid grid-cols-1 lg:grid-cols-3 gap-4">
        <div class="rounded-lg p-5 border-2 hover:border-orange-500 transition duration-150 ease-linear border-primary-500"
            role="presentation">
            <div class="card-body">
                <h6 class="font-semibold mb-4 text-lg">Revenue</h6>
                <div class="flex justify-between items-center">
                    <div>
                        <h3 class="font-bold text-2xl mb-2"><span>{{revenue | currency}}</span></h3>
                        <p>Latest update <span class="font-semibold">{{ currentDate | date: 'dd MMM'}}</span></p>
                    </div>
                    <div>
                        <mat-icon class="scale-[200%] pe-10">
                            <span class="material-symbols-outlined text-gray-500">
                                payments
                            </span>
                        </mat-icon>
                    </div>
                </div>
            </div>
        </div>
        <div class="rounded-lg p-5 border-2 hover:border-orange-500 transition duration-150 ease-linear border-primary-500"
            role="presentation">
            <div class="card-body">
                <h6 class="font-semibold mb-4 text-lg">Orders</h6>
                <div class="flex justify-between items-center">
                    <div>
                        <h3 class="font-bold text-2xl mb-2"><span>{{orders.length}}</span></h3>
                        <p>Latest update <span class="font-semibold">{{currentDate | date: 'dd MMM'}}</span></p>
                    </div>
                    <div>
                        <mat-icon class="scale-[200%] pe-10">
                            <span class="material-symbols-outlined text-gray-500">
                                receipt_long
                            </span>
                        </mat-icon>
                    </div>
                </div>
            </div>
        </div>
        <div class="rounded-lg p-5 border-2 hover:border-orange-500 transition duration-150 ease-linear border-primary-500"
            role="presentation">
            <div class="card-body">
                <h6 class="font-semibold mb-4 text-lg">Products</h6>
                <div class="flex justify-between items-center">
                    <div>
                        <h3 class="font-bold text-2xl mb-2"><span>{{products.length}}</span></h3>
                        <p>Latest update <span class="font-semibold">{{currentDate | date: 'dd MMM'}}</span></p>
                    </div>
                    <div>
                        <mat-icon class="scale-[200%] pe-10">
                            <span class="material-symbols-outlined text-gray-500">
                                egg
                            </span>
                        </mat-icon>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="grid grid-cols-1 lg:grid-cols-3 gap-4">
        <div class="card lg:col-span-2 card-border" role="presentation">
            <div
                class="border-2 hover:border-orange-500 transition duration-150 ease-linear border-primary-500 rounded-lg p-5">
                <div class="flex items-center justify-between mb-6">
                    <h4 class="font-bold text-xl">Latest Orders</h4>
                    <a routerLink="/admin/orders"
                        class="hover:bg-gray-50 transition-all rounded-lg border-gray-300 border font-medium px-3 py-2">
                        View Orders
                    </a>
                </div>
                <div class="w-full">
                    <table class="w-full">
                        <thead class="bg-[#f5f5f5]">
                            <tr>
                                <th colspan="1">Order</th>
                                <th colspan="1">Status</th>
                                <th colspan="1">Date</th>
                                <th colspan="1">Customer</th>
                                <th colspan="1">Summary</th>
                            </tr>
                        </thead>
                        <tbody>
                            @for(order of orders.slice(0, 10); track order._id) {
                            <tr>
                                <td>
                                    <span
                                        class="cursor-pointer select-none font-semibold hover:text-indigo-600">#{{order.invoiceNo}}</span>
                                </td>
                                <td>
                                    <div class="flex items-center">
                                        @if(order.paymentInfo.isPaid) {
                                        <span class="badge-dot bg-primary-600"></span>
                                        <span class="ml-2 rtl:mr-2 capitalize font-semibold text-primary-600">
                                            Paid
                                        </span>
                                        } @else {
                                        <span class="badge-dot bg-orange-500"></span>
                                        <span class="ml-2 rtl:mr-2 capitalize font-semibold text-orange-500">
                                            Pending
                                        </span>
                                        }
                                    </div>
                                </td>
                                <td>
                                    <span>{{order.createdAt | date: 'dd/MM/yyyy'}}</span>
                                </td>
                                <td>{{order.customerInfo.firstName + ' ' + order.customerInfo.firstName}}</td>
                                <td>
                                    <span>{{order.totalPrice | currency}}</span>
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="border-2 hover:border-orange-500 transition duration-150 ease-linear border-primary-500 rounded-lg p-5"
            role="presentation">
            <div class="card-body">
                <div class="flex items-center justify-between mb-4">
                    <h4 class="font-bold text-xl">Top Selling</h4>
                    <a routerLink="/admin/products"
                        class="rounded-lg border-gray-300 hover:bg-gray-50 transition-all border font-medium px-3 py-2">View
                        Products
                    </a>
                </div>
                <div class="overflow-x-auto">
                    <table class="w-full">
                        <thead class="bg-[#f5f5f5]">
                            <tr>
                                <th colspan="1">Product</th>
                                <th colspan="1">Sold</th>
                            </tr>
                        </thead>
                        <tbody>
                            @for(item of bestSelling; track item._id) {
                            <tr>
                                <td>
                                    <div class="flex items-center gap-2">
                                        <span class="avatar avatar-rounded avatar-md w-[100px]">
                                            <img class="avatar-img avatar-rounded pe-4"
                                                [src]="productUrlImg + '/' + item.productDetails.images[0]"
                                                loading="lazy">
                                        </span>
                                        <span class="font-semibold text-gray-500 text-lg">{{item.productDetails.name}}
                                        </span>
                                    </div>
                                </td>
                                <td>{{item.totalQuantity}}</td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
