// frontend-react/src/ui/NotFound.tsx
interface NotFoundProps {
  message: string;
  bigSize?: boolean;
}

export default function NotFound({ message, bigSize = true }: NotFoundProps) {
  return (
    <div className="mb-10 flex items-center justify-center py-4 text-center">
      <div className="flex flex-col items-center justify-center gap-2">
        <img
          src="https://cdni.iconscout.com/illustration/premium/thumb/product-is-empty-8044872-6430781.png?f=webp"
          width={bigSize ? 300 : 150}
          height={bigSize ? 300 : 150}
          alt="Not Found"
        />
        <h1
          className={`${bigSize ? "text-2xl" : "text-xl"} font-medium text-gray-700`}
        >
          {message}
        </h1>
      </div>
    </div>
  );
}

// frontend-angular/src/app/shared/components/not-found/not-found.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-not-found',
  standalone: true,
  imports: [],
  templateUrl: './not-found.component.html',
  styleUrl: './not-found.component.css'
})

export class NotFoundComponent {
  @Input() bigSize!: boolean;
  @Input() message!: string;
}

<div class="mb-10 flex items-center justify-center py-4 text-center">
    <div class="flex flex-col items-center justify-center gap-2">
        <img [src]="'https://cdni.iconscout.com/illustration/premium/thumb/product-is-empty-8044872-6430781.png?f=webp'"
            [width]="bigSize ? 300 : 150" [height]="bigSize ? 300 : 150" alt="Not Found" />
        <h1 [class.text-2xl]="bigSize" [class.text-xl]="!bigSize" class="font-medium text-gray-700">
            {{ message }}
        </h1>
    </div>
</div>
