// frontend-angular/src/app/features/admin/coupons/coupon-list/coupon-list.component.ts
import { Component } from '@angular/core';
import { MatIconModule } from '@angular/material/icon';
import { RouterLink } from '@angular/router';
import { ToastrService } from 'ngx-toastr';
import { DatePipe } from '@angular/common';

import { ICoupon } from '../../../../core/models/coupon.model';
import { PaginatorComponent } from '../../../../shared/components/paginator/paginator.component';
import { LoaderComponent } from '../../../../shared/components/loader/loader.component';
import { NotFoundComponent } from '../../../../shared/components/not-found/not-found.component';
import { CouponService } from '../../../../core/services/coupon.service';
import { CurrencyPipe } from '../../../../core/pipes/currency.pipe';

@Component({
  selector: 'app-coupon-list',
  standalone: true,
  imports: [MatIconModule, PaginatorComponent, RouterLink, LoaderComponent, NotFoundComponent, DatePipe, CurrencyPipe],
  templateUrl: './coupon-list.component.html',
  styleUrl: './coupon-list.component.css'
})

export class CouponListComponent {
  coupons: ICoupon[] = [];
  isLoading: boolean = false;
  totalRecords: number = 0;
  first = 0;
  rows = 10;

  constructor(
    private couponService: CouponService,
    private toast: ToastrService,
  ) { }

  ngOnInit(): void {
    this.getAllCoupons();
  }

  getAllCoupons(page: number = 0, limit: number = 10) {
    this.isLoading = true;
    this.couponService.getAllCoupons(page, limit).subscribe({
      next: (response) => {
        this.coupons = response.data;
        this.totalRecords = response.totalRecords;
        this.isLoading = false;
      },
      error: (error) => {
        if (this.coupons.length === 0) {
          this.isLoading = false;
        }
      }
    });
  }

  onDeleteCoupon(id: string) {
    if (confirm('Are you sure you want to delete this category?')) {
      this.couponService.deleteCoupon(id).subscribe({
        next: (response) => {
          this.toast.success('Category deleted successfully!');
          this.getAllCoupons();
        }
      });
    }
  }

  onPageChanged(event: any) {
    this.first = event.first;
    this.rows = event.rows;
    this.getAllCoupons(event.page + 1, event.rows);
  }
}

<div class="pb-10">
    <div class="lg:flex items-center justify-between mb-4">
        <h1 class="mb-4 lg:mb-0 text-2xl font-semibold text-stone-800">Coupons</h1>
        <div>
            <a routerLink="add"
                class="flex items-center gap-2 font-semibold text-base py-2 px-2 rounded-md bg-primary-600 text-white">
                <mat-icon>
                    <span class="material-symbols-outlined">
                        add_circle
                    </span>
                </mat-icon>
                Add Coupon
            </a>
        </div>
    </div>
    @if(isLoading) {
    <app-loader></app-loader>
    }
    @if(!coupons.length && !isLoading) {
    <app-not-found></app-not-found>
    }
    @if(coupons.length && !isLoading) {
    <div>
        <table class="w-full text-left text-gray-600">
            <thead class="bg-[#f5f5f5] text-sm">
                <tr>
                    <th class="uppercase">Code</th>
                    <th class="uppercase">Discount</th>
                    <th class="uppercase">Start Date</th>
                    <th class="uppercase">End Date</th>
                    <th class="uppercase">Actions</th>
                </tr>
            </thead>
            <tbody>
                @for(coupon of coupons; track coupon._id) {
                <tr>
                    <td>{{coupon.code}}</td>
                    <td>
                        {{coupon.discount | currency}}
                    </td>
                    <td>
                        {{coupon.startTime | date: 'dd/MM/yyy HH:mm:ss'}}
                    </td>
                    <td>
                        {{coupon.endTime | date: 'dd/MM/yyy HH:mm:ss'}}
                    </td>
                    <td>
                        <div class="flex items-center gap-3">
                            <a class="flex items-center" routerLink="edit/{{coupon._id}}">
                                <mat-icon class="scale-110">
                                    <span class="material-symbols-outlined text-blue-500">
                                        edit_square
                                    </span>
                                </mat-icon>
                            </a>
                            <button class="flex items-center" (click)="onDeleteCoupon(coupon._id)">
                                <mat-icon class="scale-110">
                                    <span class="material-symbols-outlined text-red-500">
                                        delete_forever
                                    </span>
                                </mat-icon>
                            </button>
                        </div>
                    </td>
                </tr>
                }
            </tbody>
        </table>
        <app-paginator [totalRecords]="totalRecords" [first]="first" [rows]="rows"
            (pageChangeEvent)="onPageChanged($event)"></app-paginator>
    </div>
    }
</div>

// frontend-react/src/features/admin/coupons/CouponList.tsx
import { Pagination } from "@mui/material";
import { ChangeEvent, useEffect, useState } from "react";
import { AxiosError } from "axios";
import { Link } from "react-router-dom";
import { FaRegTrashAlt } from "react-icons/fa";
import { FaCirclePlus } from "react-icons/fa6";
import { LuPencil } from "react-icons/lu";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";

import { toastUI } from "src/utils/toast";
import NotFound from "src/ui/NotFound";
import { ICoupon } from "src/interfaces/coupon";
import { deleteCoupon, getAllCoupons } from "src/services/apiCoupons";
import { convertToDateString, formatCurrency } from "src/utils/helpers";
import Loader from "src/ui/Loader";

const PER_PAGE = 10;

export default function CategoryList() {
  const [curPage, setCurPage] = useState(1);
  const [totalPages, setTotalPages] = useState(0);
  const queryClient = useQueryClient();

  const start = (curPage - 1) * PER_PAGE;
  const end = curPage * PER_PAGE;

  const handleChangePage = (event: ChangeEvent<unknown>, page: number) => {
    setCurPage(page);
  };

  const {
    data: allCoupons,
    isLoading,
    isError,
  } = useQuery<ICoupon[]>({
    queryKey: ["allCoupons"],
    queryFn: getAllCoupons,
  });
  useEffect(() => {
    if (allCoupons) {
      setTotalPages(Math.ceil(allCoupons.length / PER_PAGE));
    }
  }, [allCoupons]);

  const { mutate: deleteMutate, isPending } = useMutation<
    unknown,
    // eslint-disable-next-line
    AxiosError<any, any>,
    string
  >({
    mutationFn: (id: string) => deleteCoupon(id),
    onSuccess: () => {
      toastUI("Delete coupon successfully", "success");
      queryClient.invalidateQueries({ queryKey: ["allCoupons"] });
    },
    onError: (err) => {
      toastUI(err.response?.data.error, "error");
    },
  });

  if (isLoading) {
    return <Loader />;
  }

  if (!allCoupons?.length || isError) {
    return <NotFound message="No coupons found" bigSize={false} />;
  }

  return (
    <div
      className={`${isPending ? "pointer-events-none opacity-90" : "pointer-events-auto opacity-100"}`}
    >
      <div className="mb-4 items-center justify-between lg:flex">
        <h1 className="mb-4 text-2xl font-semibold text-stone-800 lg:mb-0">
          Coupons
        </h1>
        <div>
          <Link
            to="/admin/coupons/add"
            className="flex items-center gap-2 rounded-md bg-primary-600 px-3 py-2 text-base font-semibold text-white hover:text-white"
          >
            <FaCirclePlus />
            Add Coupon
          </Link>
        </div>
      </div>
      <div>
        <table className="w-full text-left text-gray-600">
          <thead className="bg-[#f5f5f5] text-sm">
            <tr>
              <th className="uppercase">Code</th>
              <th className="uppercase">Discount</th>
              <th className="uppercase">Start Date</th>
              <th className="uppercase">End Date</th>
              <th className="uppercase">Actions</th>
            </tr>
          </thead>
          <tbody>
            {allCoupons.slice(start, end).map((cp) => (
              <tr key={cp._id}>
                <td>{cp.code}</td>
                <td>{formatCurrency(cp.discount)}</td>
                <td>{convertToDateString(cp.startTime)}</td>
                <td>{convertToDateString(cp.endTime)}</td>
                <td>
                  <div className="flex items-center gap-4">
                    <Link
                      className="flex items-center"
                      to={`/admin/coupons/edit/${cp._id}`}
                    >
                      <LuPencil className="text-xl text-blue-500" />
                    </Link>
                    <button className="flex items-center">
                      <FaRegTrashAlt
                        className="text-xl text-red-500"
                        onClick={() => deleteMutate(cp._id)}
                      />
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        <div className="float-end mt-4">
          <Pagination
            count={totalPages}
            variant="outlined"
            shape="rounded"
            page={curPage}
            onChange={handleChangePage}
          />
        </div>
      </div>
    </div>
  );
}
