// frontend-react/src/features/admin/users/UserList.tsx
import { Pagination } from "@mui/material";
import { ChangeEvent, useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AxiosError } from "axios";

import { PUBLIC_ENDPOINTS } from "src/constants/url";
import { toastUI } from "src/utils/toast";
import { changeRole, getAllUsers } from "src/services/apiAuth";
import NotFound from "src/ui/NotFound";
import Loader from "src/ui/Loader";

const PER_PAGE = 10;

export default function UserList() {
  const [curPage, setCurPage] = useState(1);
  const [totalPages, setTotalPages] = useState(0);
  const queryClient = useQueryClient();

  const start = (curPage - 1) * PER_PAGE;
  const end = curPage * PER_PAGE;

  const handleChangePage = (event: ChangeEvent<unknown>, page: number) => {
    setCurPage(page);
  };

  const { data: users, isError } = useQuery({
    queryKey: ["allUsers"],
    queryFn: getAllUsers,
  });

  useEffect(() => {
    if (users) {
      setTotalPages(Math.ceil(users.length / PER_PAGE));
    }
  }, [users]);

  const { mutate: changeRoleMutate, isPending } = useMutation<
    unknown,
    // eslint-disable-next-line
    AxiosError<any, any>,
    { id: string; isAdmin: boolean }
  >({
    mutationFn: ({ id, isAdmin }) => changeRole(id, isAdmin),
    onSuccess: () => {
      toastUI("Updated role successfully", "success");
      queryClient.invalidateQueries({ queryKey: ["allUsers"] });
    },
    onError: (err) => {
      toastUI(err.response?.data.error, "error");
    },
  });

  const handleChangeRole = (e: ChangeEvent<HTMLSelectElement>, id: string) => {
    console.log(e.target.value);
    changeRoleMutate({ id, isAdmin: e.target.value !== "0" });
  };

  if (isPending) {
    return <Loader />;
  }

  if (!users?.length || isError) {
    return <NotFound message="No users found." bigSize={false} />;
  }

  return (
    <div>
      <div className="mb-4 items-center justify-between lg:flex">
        <h1 className="mb-4 text-2xl font-semibold text-stone-800 lg:mb-0">
          Users
        </h1>
        <div></div>
      </div>
      <div>
        <table className="w-full text-left text-gray-600">
          <thead className="bg-[#f5f5f5] text-sm">
            <tr>
              <th className="uppercase">Name</th>
              <th className="uppercase">Avatar</th>
              <th className="uppercase">Email</th>
              <th className="uppercase">Phone</th>
              <th className="uppercase">Address</th>
              <th className="uppercase">Actions</th>
            </tr>
          </thead>
          <tbody>
            {users.slice(start, end).map((u) => (
              <tr>
                <td>{u.name}</td>
                <td>
                  <img
                    src={
                      u.avatar.startsWith("https://") ||
                      u.avatar.startsWith("data:")
                        ? u.avatar
                        : PUBLIC_ENDPOINTS.IMAGE_USERS + "/" + u.avatar
                    }
                    alt={u.name}
                    className="h-10 w-10 rounded-md"
                  />
                </td>
                <td>{u.email}</td>
                <td>{u.phone ? u.phone : "Not yet"}</td>
                <td>{u.address ? u.address : "Not yet"}</td>
                <td>
                  <select
                    name="role"
                    id="role"
                    role="button"
                    onChange={(e) => handleChangeRole(e, u._id)}
                    value={u.isAdmin ? "1" : "0"}
                    className="rounded-md border border-primary-600 px-2 py-1 active:border-primary-700"
                  >
                    <option value="1">Admin</option>
                    <option value="0">User</option>
                  </select>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        <div className="float-end mt-4">
          <Pagination
            count={totalPages}
            variant="outlined"
            shape="rounded"
            page={curPage}
            onChange={handleChangePage}
          />
        </div>
      </div>
    </div>
  );
}

// frontend-angular/src/app/features/admin/users/user-list/user-list.component.ts
import { Component, OnInit } from '@angular/core';
import { ToastrService } from 'ngx-toastr';
import { MatIconModule } from '@angular/material/icon';

import { IUser } from '../../../../core/models/auth.model';
import { PUBLIC_ENDPOINTS } from '../../../../core/constants/urls';
import { LoaderComponent } from '../../../../shared/components/loader/loader.component';
import { PaginatorComponent } from '../../../../shared/components/paginator/paginator.component';
import { NotFoundComponent } from '../../../../shared/components/not-found/not-found.component';
import { AuthService } from '../../../../core/services/auth.service';

@Component({
  selector: 'app-user-list',
  standalone: true,
  imports: [MatIconModule, LoaderComponent, PaginatorComponent, NotFoundComponent],
  templateUrl: './user-list.component.html',
  styleUrl: './user-list.component.css'
})

export class UserListComponent implements OnInit {
  users: IUser[] = [];
  admin!: IUser;
  imageUrl = PUBLIC_ENDPOINTS.IMAGE_USERS;
  isLoading: boolean = false;
  totalRecords: number = 0;
  first = 0;
  rows = 10;

  constructor(
    private authService: AuthService,
    private toast: ToastrService,
  ) { }

  ngOnInit(): void {
    this.getAllUsers();
    this.authService.userProfile$.subscribe(user => {
      if (user) {
        this.admin = user;
      }
    });
  }

  getAllUsers(page: number = 0, limit: number = 10) {
    this.isLoading = true;
    this.authService.getAllUsers(page, limit).subscribe({
      next: (response) => {
        this.users = response.data.filter(user => user._id !== this.admin._id);
        this.totalRecords = response.totalRecords;
        this.isLoading = false;
      },
      error: (error) => {
        if (this.users.length === 0) {
          this.isLoading = false;
        }
      }
    });
  }

  onChangeRole($event: Event, id: string) {
    const selectEl = $event.target as HTMLSelectElement;
    this.authService.changeRole(id, selectEl.value === '0' ? false : true).subscribe({
      next: (res) => {
        console.log(res);
        this.toast.success("Updated user role successfully");
      },
      error: () => {
        this.toast.error("Failed to update user role");
      }
    });
  }

  onPageChanged(event: any) {
    console.log(event);
    this.first = event.first;
    this.rows = event.rows;
    this.getAllUsers(event.page + 1, event.rows);
  }
}

<div class="pb-10">
    <div class="lg:flex items-center justify-between mb-4">
        <h1 class="mb-4 lg:mb-0 text-2xl font-semibold text-stone-800">Users</h1>
        <div>
            <!-- <a routerLink="add"
                class="flex items-center gap-2 font-semibold text-base py-2 px-2 rounded-md bg-primary-600 text-white">
                <mat-icon>
                    <span class="material-symbols-outlined">
                        add_circle
                    </span>
                </mat-icon>
                Add Category
            </a> -->
        </div>
    </div>
    @if(isLoading) {
    <app-loader></app-loader>
    }

    @if(!users.length && !isLoading) {
    <app-not-found></app-not-found>
    }

    @if(!isLoading && users.length) {
    <div>
        <table class="w-full text-left text-gray-600">
            <thead class="bg-[#f5f5f5] text-sm">
                <tr>
                    <th class="uppercase">Name</th>
                    <th class="uppercase">Avatar</th>
                    <th class="uppercase">Email</th>
                    <th class="uppercase">Phone</th>
                    <th class="uppercase">Address</th>
                    <th class="uppercase">Actions</th>
                </tr>
            </thead>
            <tbody>
                @for(user of users; track user._id) {
                <tr>
                    <td>{{user.name}}</td>
                    <td>
                        <img [src]="user.avatar.startsWith('https://') ? user.avatar : imageUrl + '/' + user.avatar"
                            alt="{{user.name}}" class="w-10 h-10 rounded-md">
                    </td>
                    <td>{{user.email}}</td>
                    <td>{{user.phone ? user.phone : 'Not yet'}}</td>
                    <td>{{user.address ? user.address : 'Not yet'}}</td>
                    <td>
                        <select name="role" id="role" role="button" (change)="onChangeRole($event, user._id)"
                            class="border border-primary-600 py-1 px-2 rounded-md active:border-primary-700">
                            <option value="1" [selected]="user.isAdmin">Admin</option>
                            <option value="0" [selected]="!user.isAdmin">User</option>
                        </select>
                    </td>
                </tr>
                }
            </tbody>
        </table>
        <app-paginator [totalRecords]="totalRecords" [first]="first" [rows]="rows"
            (pageChangeEvent)="onPageChanged($event)"></app-paginator>
    </div>
    }
</div>
