// frontend-react/src/features/admin/coupons/CouponEditor.tsx
import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AxiosError } from "axios";
import { useEffect } from "react";
import { useForm } from "react-hook-form";
import { IoSaveSharp } from "react-icons/io5";
import { useNavigate, useParams } from "react-router-dom";

import { ICreateCoupon } from "src/interfaces/coupon";
import {
  createCoupon,
  getCouponById,
  updateCoupon,
} from "src/services/apiCoupons";
import Input from "src/ui/Input";
import Loader from "src/ui/Loader";
import NotFound from "src/ui/NotFound";
import { toastUI } from "src/utils/toast";
import { createCouponSchema } from "src/zods/coupon";

export default function CouponEditor() {
  const queryClient = useQueryClient();
  const navigate = useNavigate();

  const { id } = useParams();

  const {
    data: coupon,
    isLoading,
    isError,
  } = useQuery({
    queryKey: ["coupon", id],
    queryFn: () => getCouponById(id as string),
    enabled: !!id,
  });

  const {
    register,
    handleSubmit,
    setValue,
    formState: { errors },
  } = useForm<ICreateCoupon>({
    resolver: zodResolver(createCouponSchema),
    defaultValues: {
      code: "",
      discount: 0,
      endTime: "",
      startTime: "",
    },
  });

  useEffect(() => {
    if (coupon) {
      setValue("code", coupon.code);
      setValue("discount", coupon.discount);
      setValue("startTime", coupon.startTime.substring(0, 16));
      setValue("endTime", coupon.endTime.substring(0, 16));
    }
  }, [coupon, setValue]);

  const { mutate: couponMutate, isPending } = useMutation<
    unknown,
    // eslint-disable-next-line
    AxiosError<any, any>,
    ICreateCoupon
  >({
    mutationFn: (data: ICreateCoupon) =>
      id ? updateCoupon(data, id) : createCoupon(data),
    onSuccess: () => {
      toastUI(
        `${id ? "Update" : "Create new"} coupon successfully.`,
        "success",
      );
      queryClient.invalidateQueries({ queryKey: ["coupon", id] });
      queryClient.invalidateQueries({ queryKey: ["allCoupons"] });
      navigate("/admin/coupons/list");
    },
    onError: (err) => {
      toastUI(err.response?.data.error, "error");
    },
  });

  const onSubmit = (data: ICreateCoupon) => {
    couponMutate(data);
  };

  if (isLoading) {
    return <Loader />;
  }

  if (isError) {
    return <NotFound message="Coupon not found." bigSize={false} />;
  }

  return (
    <div>
      <div className="mb-4 items-center justify-between lg:flex">
        <h1 className="mb-4 text-2xl font-medium text-stone-800 lg:mb-0">
          {id ? "Edit Coupon" : "Add New Coupon"}
        </h1>
      </div>
      <div className="w-full">
        <form encType="multipart/form-data" onSubmit={handleSubmit(onSubmit)}>
          <div className="flex w-full gap-6 pb-16">
            <div className="w-3/5">
              <div className="mt-5">
                <Input
                  errors={errors}
                  label="Coupon Code"
                  name="code"
                  placeholder="Enter coupon code"
                  register={register}
                  type="text"
                />
              </div>
              <div className="mt-5">
                <Input
                  min={1}
                  errors={errors}
                  label="Discount"
                  name="discount"
                  placeholder="Enter coupon discount"
                  register={register}
                  type="number"
                />
              </div>
              <div className="mt-5">
                <Input
                  errors={errors}
                  label="Start Time"
                  name="startTime"
                  placeholder="Enter start time"
                  register={register}
                  type="datetime-local"
                />
              </div>
              <div className="mt-5">
                <Input
                  errors={errors}
                  label="End Time"
                  name="endTime"
                  placeholder="Enter end time"
                  register={register}
                  type="datetime-local"
                />
              </div>
            </div>
          </div>
          <div className="sticky bottom-0 -mx-8 flex items-center justify-between border-t border-gray-200 bg-white px-8 py-4">
            <div></div>
            <div className="items-center gap-3 md:flex">
              <button
                className="button radius-round rounded-md border border-gray-300 bg-white px-3 py-2 text-base text-gray-600 hover:bg-gray-50 active:bg-gray-100 ltr:mr-3 rtl:ml-3"
                type="button"
              >
                Discard
              </button>
              <button
                disabled={isPending}
                className="button radius-round rounded-md bg-primary-600 px-3 py-2 text-base text-white hover:bg-primary-700 active:bg-primary-700"
                type="submit"
              >
                <span className="flex items-center gap-2">
                  <IoSaveSharp />
                  <span>Save</span>
                </span>
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  );
}

// frontend-angular/src/app/features/admin/coupons/coupon-editor/coupon-editor.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ToastrService } from 'ngx-toastr';
import { Subscription } from 'rxjs';
import { ActivatedRoute, Router } from '@angular/router';
import { MatIconModule } from '@angular/material/icon';

import { ICoupon } from '../../../../core/models/coupon.model';
import { CouponService } from '../../../../core/services/coupon.service';

@Component({
  selector: 'app-coupon-editor',
  standalone: true,
  imports: [ReactiveFormsModule, MatIconModule],
  templateUrl: './coupon-editor.component.html',
  styleUrl: './coupon-editor.component.css'
})
export class CouponEditorComponent {
  private routeSub!: Subscription;
  data: ICoupon | null = null;
  editorForm!: FormGroup;

  constructor(
    private formBuilder: FormBuilder,
    private couponService: CouponService,
    private route: ActivatedRoute,
    private router: Router,
    private toast: ToastrService
  ) {
    this.editorForm = this.formBuilder.group({
      code: new FormControl('', [Validators.required]),
      discount: new FormControl('', [Validators.required]),
      startDate: new FormControl('', [Validators.required]),
      endDate: new FormControl('', [Validators.required]),
    });
  }

  ngOnInit() {
    this.routeSub = this.route.params.subscribe((params) => {
      if (params['id']) {
        this.getCouponById(params['id']);
      }
    });
  }

  ngOnDestroy() {
    this.routeSub.unsubscribe();
  }

  getCouponById(id: string) {
    this.couponService.getCouponById(id).subscribe((response) => {
      this.data = response.data;
      this.editorForm.patchValue(response.data);
    });
  }

  onSubmit() {
    console.log(this.editorForm.value);
    if (this.editorForm.valid) {
      if (this.data) {
        this.couponService.updateCoupon(this.data._id, {
          ...this.editorForm.value,
          startTime: new Date(this.editorForm.value.startDate).toISOString(),
          endTime: new Date(this.editorForm.value.endDate).toISOString(),
        }).subscribe((response) => {
          this.toast.success('Coupon updated successfully!');
        });
      } else {
        this.couponService.createCoupon({
          ...this.editorForm.value,
          startTime: new Date(this.editorForm.value.startDate).toISOString(),
          endTime: new Date(this.editorForm.value.endDate).toISOString(),
        }).subscribe((response) => {
          this.toast.success('Coupon created successfully!');
          this.router.navigate(['/admin/coupons']);
        });
      }
    } else {
      this.editorForm.markAllAsTouched();
    }
  }
}

<div>
    <div class="lg:flex items-center justify-between mb-4">
        <h1 class="mb-4 lg:mb-0 text-2xl font-medium text-stone-800">{{data ? 'Edit Coupon' : 'Add New Coupon'}}
        </h1>
    </div>
    <div class="w-full">
        <form [formGroup]="editorForm" (ngSubmit)="onSubmit()" enctype="multipart/form-data">
            <div class="flex w-full gap-6 pb-16">
                <div class="w-3/5">
                    <div class="mt-5">
                        <label for="name" class="block text-gray-500 font-medium mb-2">Coupon Code</label>
                        <input type="text"
                            class="h-11 border focus:outline-primary-600 border-gray-300 rounded-lg py-3 px-5 w-full"
                            placeholder="Code" id="code" formControlName="code">
                        @if(editorForm.get('code')?.hasError('required') && editorForm.get('code')?.touched) {
                        <small class="text-red-600 text-[15px] pt-1 inline-block">(*) Code is required</small>
                        }
                    </div>
                    <div class="mt-5">
                        <label for="name" class="block text-gray-500 font-medium mb-2">Coupon discount</label>
                        <input type="number" step="0.01"
                            class="h-11 border focus:outline-primary-600 border-gray-300 rounded-lg py-3 px-5 w-full"
                            placeholder="Discount" id="discount" formControlName="discount">
                        @if(editorForm.get('discount')?.hasError('required') && editorForm.get('discount')?.touched) {
                        <small class="text-red-600 text-[15px] pt-1 inline-block">(*) Discount is required</small>
                        }
                    </div>
                    <div class="mt-5">
                        <label for="name" class="block text-gray-500 font-medium mb-2">Start Date</label>
                        <input type="date"
                            class="h-11 border focus:outline-primary-600 border-gray-300 rounded-lg py-3 px-5 w-full"
                            placeholder="Start Date" id="startDate" formControlName="startDate">
                        @if(editorForm.get('startDate')?.hasError('required') && editorForm.get('startDate')?.touched) {
                        <small class="text-red-600 text-[15px] pt-1 inline-block">(*) Start date is required</small>
                        }
                    </div>
                    <div class="mt-5">
                        <label for="name" class="block text-gray-500 font-medium mb-2">End Date</label>
                        <input type="date"
                            class="h-11 border focus:outline-primary-600 border-gray-300 rounded-lg py-3 px-5 w-full"
                            placeholder="End Date" id="endDate" formControlName="endDate">
                        @if(editorForm.get('endDate')?.hasError('required') && editorForm.get('endDate')?.touched) {
                        <small class="text-red-600 text-[15px] pt-1 inline-block">(*) End date is required</small>
                        }
                    </div>
                </div>
            </div>
            <div
                class="sticky bottom-0 -mx-8 flex items-center justify-between border-t border-gray-200 bg-white px-8 py-4 pb-10">
                <div></div>
                <div class="items-center gap-3 md:flex">
                    <button
                        class="button radius-round rounded-md border border-gray-300 bg-white px-3 py-2 text-base text-gray-600 hover:bg-gray-50 active:bg-gray-100 ltr:mr-3 rtl:ml-3"
                        type="button">
                        Discard
                    </button>
                    <button
                        class="button radius-round rounded-md bg-primary-600 px-3 py-2 text-base text-white hover:bg-primary-700 active:bg-primary-700"
                        type="submit">
                        <span class="flex items-center justify-center gap-2">
                            <mat-icon>
                                <span class="material-symbols-outlined">
                                    save
                                </span>
                            </mat-icon>
                            <span class="ltr:ml-1 rtl:mr-1">Save</span>
                        </span>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
