// frontend-angular/src/app/shared/components/product-item/product-item.component.ts
import { Component, Input } from '@angular/core';
import { MatIconModule } from '@angular/material/icon';
import { PUBLIC_ENDPOINTS } from '../../../core/constants/urls';
import { IProduct } from '../../../core/models/products.model';
import { CartService } from '../../../core/services/cart.service';
import { CurrencyPipe } from '../../../core/pipes/currency.pipe';

@Component({
  selector: 'app-product-item',
  standalone: true,
  imports: [MatIconModule, CurrencyPipe],
  templateUrl: './product-item.component.html',
  styleUrl: './product-item.component.css'
})

export class ProductItemComponent {
  @Input() product!: IProduct;
  imageUrl = PUBLIC_ENDPOINTS.IMAGE_PRODUCTS;

  constructor(private cartService: CartService) { }

  onAddToCart(product: IProduct) {
    const item = {
      id: product._id,
      image: product.images[0],
      name: product.name,
      quantity: 1,
      price: product.price,
      category: product.categoryId.name!,
    };
    this.cartService.addToCart(item);
  }
}

<li>
    <div class="relative overflow-hidden rounded-md bg-white px-2 py-3 shadow-sm">
        <div class="absolute left-0 top-0 z-10 rounded-full bg-gray-100 px-2 py-0 text-xs font-medium text-primary-600">
            @if(product.quantity > 0) {
            <span>
                Stock:
                <span class="pl-1 font-bold text-orange-700">
                    {{product.quantity}}
                </span>
            </span>
            } @else {
            <span class="pl-1 font-bold text-orange-700">
                Stock out
            </span>
            }
        </div>
        @if(product.orgPrice > product.price) {
        <div
            class="text-dark absolute right-0 top-0 z-10 rounded bg-orange-500 px-2 py-1 text-xs font-medium text-white">
            {{((product.orgPrice - product.price) / product.orgPrice * 100).toFixed(1)}} Off
        </div>
        }
        <div
            class="flex cursor-pointer items-center justify-center overflow-hidden px-2 py-3 transition-transform duration-300 ease-in-out hover:scale-105 lg:px-4 lg:py-5">
            <img src="{{imageUrl}}/{{product.images[0]}}" alt={{product.name}} class="h-40 w-40 object-cover" />
        </div>
        <div class="px-2 pb-2 text-start">
            <h3 class="mb-2">{{product.name}}</h3>
            <div class="flex items-center justify-between">
                <div>
                    <span class="block text-lg font-semibold">
                        {{product.price | currency}}
                    </span>
                    <del class="text-base text-gray-400">
                        ${{product.orgPrice | currency}}
                    </del>
                </div>
                <span
                    class="flex items-center cursor-pointer rounded-md border border-gray-200 p-2 text-primary-600 hover:bg-primary-600 hover:text-white"
                    (click)="onAddToCart(product)">
                    <mat-icon>
                        <span class="material-symbols-outlined">
                            add_shopping_cart
                        </span>
                    </mat-icon>
                </span>
            </div>
        </div>
    </div>
</li>

// frontend/src/ui/ProductItem.tsx
import { BsBagPlusFill } from "react-icons/bs";

export default function ProductItem() {
  return (
    <li>
      <div className="relative overflow-hidden rounded-md bg-white px-2 py-3">
        <div className="absolute left-0 top-0 z-10 rounded-full bg-gray-100 px-2 py-0 text-xs font-medium text-primary-600">
          <span>Stock: </span>
          <span className="pl-1 font-bold text-orange-700">11</span>
        </div>
        <div className="text-dark absolute right-0 top-0 z-10 rounded bg-orange-500 px-2 py-1 text-xs font-medium text-white">
          20% Off
        </div>
        <img
          src="https://kachabazar-store-nine.vercel.app/_next/image?url=https%3A%2F%2Fi.ibb.co%2F9g7vDQJ%2FHimalaya-Baby-Powder-100g.jpg&w=1200&q=75"
          alt=""
        />
        <div className="text-start">
          <h3 className="mb-2">Himalaya Powder</h3>
          <div className="flex items-center justify-between">
            <div>
              <span className="block text-lg font-semibold">$160.9</span>
              <del className="text-base text-gray-400">$188.8</del>
            </div>
            <span className="cursor-pointer rounded-md border border-gray-200 p-2 text-primary-600 hover:bg-primary-600 hover:text-white">
              <BsBagPlusFill className="text-lg text-inherit" />
            </span>
          </div>
        </div>
      </div>
    </li>
  );
}
