// frontend-angular/src/app/features/admin/products/product-list/product-list.component.ts
import { Component, OnInit } from '@angular/core';
import { MatIconModule } from '@angular/material/icon';

import { IProduct } from '../../../../core/models/products.model';
import { PUBLIC_ENDPOINTS } from '../../../../core/constants/constants';
import { ProductsService } from '../../../../core/services/products.service';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-product-list',
  standalone: true,
  imports: [MatIconModule, RouterLink],
  templateUrl: './product-list.component.html',
  styleUrl: './product-list.component.css'
})
export class ProductListComponent implements OnInit {
  products: IProduct[] = [];
  imageUrl = PUBLIC_ENDPOINTS.IMAGE_PRODUCTS;

  constructor(private productsService: ProductsService) { }

  ngOnInit(): void {
    this.getAllProducts();
  }

  getAllProducts() {
    this.productsService.getAllProducts().subscribe({
      next: (response) => {
        this.products = response.data;
      }
    });
  }
}
<div>
    <div class="lg:flex items-center justify-between mb-4">
        <h1 class="mb-4 lg:mb-0 text-2xl font-medium text-stone-800">Products</h1>
        <div>
            <a routerLink="add"
                class="flex items-center gap-2 font-semibold text-base py-2 px-2 rounded-md bg-primary-600 text-white">
                <mat-icon>
                    <span class="material-symbols-outlined">
                        add_circle
                    </span>
                </mat-icon>
                Add Product
            </a>
        </div>
    </div>
    <div>
        <table class="w-full text-left text-gray-600">
            <thead class="bg-[#f5f5f5] text-sm">
                <tr>
                    <th class="uppercase">Name</th>
                    <th class="uppercase">Category</th>
                    <th class="uppercase">Quantity</th>
                    <th class="uppercase">Hot</th>
                    <th class="uppercase">Price</th>
                    <th class="uppercase">Actions</th>
                </tr>
            </thead>
            <tbody>
                @for(product of products; track product._id) {
                <tr>
                    <td class="flex items-center">
                        <div>
                            <img class="w-10 h-10 rounded-md pe-2" src="{{imageUrl}}/{{product.images[0]}}"
                                alt="{{product.name}}" />
                        </div>
                        <span>{{product.name}}</span>
                    </td>
                    <td>{{product.categoryId.name}}</td>
                    <td>{{product.quantity}}</td>
                    <td>
                        @if(product.hot) {
                        <span class="text-primary-600">Yes</span>
                        } @else {
                        <span class="text-red-600">No</span>
                        }
                    </td>
                    <td>${{product.price}}</td>
                    <td>
                        <div class="flex items-center gap-3">
                            <button class="flex items-center">
                                <mat-icon class="scale-110">
                                    <span class="material-symbols-outlined text-blue-500">
                                        edit_square
                                    </span>
                                </mat-icon>
                            </button>
                            <button class="flex items-center">
                                <mat-icon class="scale-110">
                                    <span class="material-symbols-outlined text-red-500">
                                        delete_forever
                                    </span>
                                </mat-icon>
                            </button>
                        </div>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>

// frontend-react/src/features/admin/products/ProductList.tsx
import { Link } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { FaCirclePlus } from "react-icons/fa6";
import { LuPencil } from "react-icons/lu";
import { FaRegTrashAlt } from "react-icons/fa";

import { getAllProducts } from "src/services/apiProducts";
import { PUBLIC_ENDPOINTS } from "src/constants/url";
import { formatCurrency } from "src/utils/helpers";

export default function ProductList() {
  const { data: products, error } = useQuery({
    queryKey: ["allProducts"],
    queryFn: getAllProducts,
  });

  return (
    <div>
      <div className="mb-4 items-center justify-between lg:flex">
        <h1 className="mb-4 text-2xl font-semibold text-stone-800 lg:mb-0">
          Products
        </h1>
        <div>
          <Link
            to="/admin/products/add"
            className="flex items-center gap-2 rounded-md bg-primary-600 px-3 py-2 text-base font-semibold text-white hover:text-white"
          >
            <FaCirclePlus />
            Add Product
          </Link>
        </div>
      </div>
      <div>
        <table className="w-full text-left text-gray-600">
          <thead className="bg-[#f5f5f5] text-sm">
            <tr>
              <th className="uppercase">Name</th>
              <th className="uppercase">Category</th>
              <th className="uppercase">Quantity</th>
              <th className="uppercase">Hot</th>
              <th className="uppercase">Price</th>
              <th className="uppercase">Actions</th>
            </tr>
          </thead>
          <tbody>
            {products?.map((p) => (
              <tr key={p._id}>
                <td className="flex items-center">
                  <div>
                    <img
                      className="h-10 w-10 rounded-md pe-2"
                      src={PUBLIC_ENDPOINTS.IMAGE_PRODUCTS + "/" + p.images[0]}
                      alt={p.name}
                    />
                  </div>
                  <span>{p.name}</span>
                </td>
                <td>{p.categoryId.name}</td>
                <td>{p.quantity}</td>
                <td>
                  {p.hot ? (
                    <span className="text-primary-600">Yes</span>
                  ) : (
                    <span className="text-red-600">No</span>
                  )}
                </td>
                <td>{formatCurrency(p.price)}</td>
                <td>
                  <div className="flex items-center gap-4">
                    <Link
                      className="flex items-center"
                      to="/admin/products/edit/"
                    >
                      <LuPencil className="text-xl text-blue-500" />
                    </Link>
                    <button className="flex items-center">
                      <FaRegTrashAlt className="text-xl text-red-500" />
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
