// frontend-angular/src/app/features/admin/categories/category-list/category-list.component.ts
import { Component, OnInit } from '@angular/core';
import { MatIconModule } from '@angular/material/icon';
import { RouterLink } from '@angular/router';

import { ICategory } from '../../../../core/models/categories.model';
import { PUBLIC_ENDPOINTS } from '../../../../core/constants/constants';
import { CategoriesService } from '../../../../core/services/categories.service';
import { ToastrService } from 'ngx-toastr';

@Component({
  selector: 'app-admin-category-list',
  standalone: true,
  imports: [MatIconModule, RouterLink],
  templateUrl: './category-list.component.html',
  styleUrl: './category-list.component.css'
})

export class CategoryListComponent implements OnInit {
  categories: ICategory[] = [];
  imageUrl = PUBLIC_ENDPOINTS.IMAGE_CATEGORIES;

  constructor(
    private categoriesService: CategoriesService,
    private toast: ToastrService
  ) { }

  ngOnInit(): void {
    this.getAllCategories();
  }

  getAllCategories() {
    this.categoriesService.getAllCategories().subscribe({
      next: (response) => {
        this.categories = response.data;
      }
    });
  }

  onDeleteCategory(id: string) {
    this.categoriesService.deleteCategory(id).subscribe({
      next: (response) => {
        this.toast.success('Category deleted successfully!');
      }
    });
  }
}
<div>
    <div class="lg:flex items-center justify-between mb-4">
        <h1 class="mb-4 lg:mb-0 text-2xl font-medium text-stone-800">Categories</h1>
        <div>
            <a routerLink="add"
                class="flex items-center gap-2 font-semibold text-base py-2 px-2 rounded-md bg-primary-600 text-white">
                <mat-icon>
                    <span class="material-symbols-outlined">
                        add_circle
                    </span>
                </mat-icon>
                Add Category
            </a>
        </div>
    </div>
    <div>
        <table class="w-full text-left text-gray-600">
            <thead class="bg-[#f5f5f5] text-sm">
                <tr>
                    <th class="uppercase">Name</th>
                    <th class="uppercase">Image</th>
                    <th class="uppercase">Actions</th>
                </tr>
            </thead>
            <tbody>
                @for(category of categories; track category._id) {
                <tr>
                    <td>{{category.name}}</td>
                    <td>
                        <img src="{{imageUrl}}/{{category.image}}" alt="{{category.name}}" class="w-10 h-10 rounded-md">
                    </td>
                    <td>
                        <div class="flex items-center gap-3">
                            <a class="flex items-center" routerLink="edit/{{category._id}}">
                                <mat-icon class="scale-110">
                                    <span class="material-symbols-outlined text-blue-500">
                                        edit_square
                                    </span>
                                </mat-icon>
                            </a>
                            <button class="flex items-center" (click)="onDeleteCategory(category._id)">
                                <mat-icon class="scale-110">
                                    <span class="material-symbols-outlined text-red-500">
                                        delete_forever
                                    </span>
                                </mat-icon>
                            </button>
                        </div>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>

// frontend-react/src/features/admin/categories/CategoryList.tsx
import { Link } from "react-router-dom";
import { FaRegTrashAlt } from "react-icons/fa";
import { FaCirclePlus } from "react-icons/fa6";
import { LuPencil } from "react-icons/lu";
import { useQuery } from "@tanstack/react-query";

import { getAllCategories } from "src/services/apiCategories";
import { PUBLIC_ENDPOINTS } from "src/constants/url";

export default function CategoryList() {
  const { data: categories, error } = useQuery({
    queryKey: ["allCategories"],
    queryFn: getAllCategories,
  });

  return (
    <div>
      <div className="mb-4 items-center justify-between lg:flex">
        <h1 className="mb-4 text-2xl font-semibold text-stone-800 lg:mb-0">
          Categories
        </h1>
        <div>
          <Link
            to="/admin/categories/add"
            className="flex items-center gap-2 rounded-md bg-primary-600 px-3 py-2 text-base font-semibold text-white hover:text-white"
          >
            <FaCirclePlus />
            Add Category
          </Link>
        </div>
      </div>
      <div>
        <table className="w-full text-left text-gray-600">
          <thead className="bg-[#f5f5f5] text-sm">
            <tr>
              <th className="uppercase">Name</th>
              <th className="uppercase">Image</th>
              <th className="uppercase">Actions</th>
            </tr>
          </thead>
          <tbody>
            {categories?.map((c) => (
              <tr key={c._id}>
                <td>{c.name}</td>
                <td>
                  <img
                    src={PUBLIC_ENDPOINTS.IMAGE_CATEGORIES + "/" + c.image}
                    alt={c.name}
                    className="h-10 w-10 rounded-md"
                  />
                </td>
                <td>
                  <div className="flex items-center gap-4">
                    <Link
                      className="flex items-center"
                      to={`/admin/categories/edit/${c._id}`}
                    >
                      <LuPencil className="text-xl text-blue-500" />
                    </Link>
                    <button className="flex items-center">
                      <FaRegTrashAlt className="text-xl text-red-500" />
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
