// frontend-react/src/features/admin/orders/OrderDetail.tsx
import { useParams } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AxiosError } from "axios";
import {
  MdDateRange,
  MdOutlineEmail,
  MdOutlineLocalPhone,
  MdOutlineLocationOn,
} from "react-icons/md";

import { toastUI } from "src/utils/toast";
import { getOrdersById, updateOrder } from "src/services/apiOrder";
import NotFound from "src/ui/NotFound";
import { convertToDateString, formatCurrency } from "src/utils/helpers";
import { PUBLIC_ENDPOINTS } from "src/constants/url";
import { TOrderStatus } from "src/interfaces/order";

export default function OrderDetail() {
  const queryClient = useQueryClient();

  const { id } = useParams();

  const { data: order, isError } = useQuery({
    queryKey: ["orderDetail", id],
    queryFn: () => getOrdersById(id as string),
    enabled: !!id,
  });

  const { mutate: updatePaidMutate, isPending: isPendingPaid } = useMutation<
    unknown,
    // eslint-disable-next-line
    AxiosError<any, any>,
    string
  >({
    mutationFn: (id: string) =>
      updateOrder(id, { paymentInfo: { ...order!.paymentInfo, isPaid: true } }),
    onSuccess: () => {
      toastUI("Order is paid", "success");
      queryClient.invalidateQueries({ queryKey: ["orderDetail", id] });
      queryClient.invalidateQueries({ queryKey: ["allOrders"] });
    },
    onError: (err) => {
      toastUI(err.response?.data.error, "error");
    },
  });

  const { mutate: statusMutate, isPending: isPendingStatus } = useMutation<
    unknown,
    // eslint-disable-next-line
    AxiosError<any, any>,
    { id: string; status: TOrderStatus }
  >({
    mutationFn: ({ id, status }) => updateOrder(id, { status: status }),
    onSuccess: () => {
      toastUI("Status order is changed", "success");
      queryClient.invalidateQueries({ queryKey: ["orderDetail", id] });
      queryClient.invalidateQueries({ queryKey: ["allOrders"] });
    },
    onError: (err) => {
      toastUI(err.response?.data.error, "error");
    },
  });

  if (!order || !isError) {
    return <NotFound message="No order found" bigSize={false} />;
  }

  return (
    <div className="container mx-auto h-full">
      <div className="mb-6">
        <div className="mb-2 flex items-center">
          <h3 className="text-2xl font-semibold">
            <span>Order </span>
            <span className="ltr:ml-2 rtl:mr-2">#{order.invoiceNo}</span>
          </h3>
          <select
            className="ms-8 w-[160px] cursor-pointer rounded-md border border-primary-600 px-1 py-2"
            name="status"
            id="status"
            disabled={isPendingStatus || isPendingPaid}
            onChange={(e) =>
              statusMutate({
                id: order._id,
                status: e.target.value as TOrderStatus,
              })
            }
            value={order.status}
          >
            {order.status === "Cancelled" && (
              <option value="Cancelled">Cancelled</option>
            )}
            {order.status !== "Cancelled" && (
              <>
                {order.status !== "Delivered" &&
                  order.status !== "Confirmed" && (
                    <option value="Pending">Pending</option>
                  )}
                {order.status !== "Delivered" && (
                  <option value="Confirmed">Confirmed</option>
                )}
                {(order.status === "Confirmed" ||
                  order.status === "Delivered") && (
                  <option value="Delivered">Delivered</option>
                )}
              </>
            )}
          </select>
        </div>
        <span className="flex items-center">
          <MdDateRange className="text-2xl" />
          <span className="ms-2 rtl:mr-1">
            {convertToDateString(order.createdAt)}
          </span>
        </span>
      </div>
      <div className="gap-6 xl:flex">
        <div className="w-full">
          <div className="card-border mb-4 border-0" role="presentation">
            <div>
              <div className="overflow-x-auto">
                <table className="w-full text-start">
                  <thead>
                    <tr>
                      <th>Product</th>
                      <th>Price</th>
                      <th>Quantity</th>
                      <th>Total</th>
                    </tr>
                  </thead>
                  <tbody>
                    {order.orderItems.map((item) => (
                      <tr>
                        <td>
                          <div className="flex items-center gap-3">
                            <span
                              className="avatar avatar-rounded"
                              style={{
                                width: "50px",
                                height: "50px",
                                minWidth: "50px",
                                lineHeight: "50px",
                                fontSize: "12px",
                              }}
                            >
                              <img
                                className="avatar-img avatar-rounded"
                                src={
                                  PUBLIC_ENDPOINTS.IMAGE_PRODUCTS +
                                  "/" +
                                  item.product.images[0]
                                }
                                loading="lazy"
                                alt="Product"
                              />
                            </span>
                            <div className="ltr:ml-2 rtl:mr-2">
                              <h6>{item.product.name}</h6>
                            </div>
                          </div>
                        </td>
                        <td>
                          <span>{item.product.price}</span>
                        </td>
                        <td>{item.quantity}</td>
                        <td>
                          <span>
                            {formatCurrency(item.quantity * item.product.price)}
                          </span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
        <div className="w-full xl:max-w-[360px]">
          <div className="card card-border" role="presentation">
            <div className="card-body">
              <h5 className="mb-2 text-2xl font-semibold">Customer</h5>
              <span className="group flex items-center justify-between">
                <div className="flex items-center">
                  <div className="ltr:ml-2 rtl:mr-2">
                    <div className="font-semibold">
                      Full Name:{" "}
                      {order.customerInfo.firstName +
                        " " +
                        order.customerInfo.lastName}
                    </div>
                    <span>
                      <span className="font-semibold">11 </span>previous orders
                    </span>
                  </div>
                </div>
              </span>
              <hr className="my-5" />
              <span className="mb-4 flex items-center gap-2 text-gray-500">
                <MdOutlineEmail className="text-xl" />
                <span className="font-semibold">
                  {order.customerInfo.email}
                </span>
              </span>
              <span className="flex items-center gap-2 text-gray-500">
                <MdOutlineLocalPhone className="text-xl" />
                <span className="font-semibold">
                  {order.customerInfo.phone}
                </span>
              </span>
              <hr className="my-5" />
              <h6 className="mb-4 flex items-center gap-2 text-gray-500">
                <MdOutlineLocationOn className="text-xl" />
                <span>Shipping Address</span>
              </h6>
              <address className="not-italic text-gray-500">
                <div className="mb-1">
                  Zip Code: {order.shippingInfo.zipCode}
                </div>
                <div className="mb-1">Street: {order.shippingInfo.address}</div>
                <div className="mb-1">City: {order.shippingInfo.city}</div>
                <div>Country: {order.shippingInfo.country}</div>
              </address>
              <div className="mt-4 pb-20" role="presentation">
                <div className="card-body">
                  <h5 className="mb-2 text-2xl font-semibold">
                    Payment Summary
                  </h5>
                  <ul className="text-gray-500">
                    <li className="mb-3 flex items-center justify-between">
                      <span>Discount: </span>
                      <span className="font-semibold">
                        <span>{formatCurrency(order.discount)}</span>
                      </span>
                    </li>
                    <li className="mb-3 flex items-center justify-between">
                      <span>Delivery fee: </span>
                      <span className="font-semibold">
                        <span>
                          {formatCurrency(order.shippingInfo.cost || 10)}
                        </span>
                      </span>
                    </li>
                    <li className="flex items-center justify-between">
                      <span>Total: </span>
                      <span className="font-semibold">
                        <span>{formatCurrency(order.totalPrice)}</span>
                      </span>
                    </li>
                  </ul>
                </div>
                <div className="mt-3 w-full text-center">
                  {order.paymentInfo.isPaid ? (
                    <span className="block w-full rounded-lg bg-red-600 py-2 font-semibold text-white transition-all">
                      This order is paid.
                    </span>
                  ) : (
                    <button
                      disabled={isPendingStatus || isPendingPaid}
                      className="w-full rounded-lg bg-primary-600 py-2 font-semibold text-white transition-all hover:bg-primary-700"
                      onClick={() => updatePaidMutate(order._id)}
                    >
                      Paid ?
                    </button>
                  )}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// frontend-angular/src/app/features/admin/order/order-detail/order-detail.component.ts
import { Component, OnDestroy, OnInit, inject } from '@angular/core';
import { MatIconModule } from '@angular/material/icon';
import { ActivatedRoute } from '@angular/router';
import { DatePipe } from '@angular/common';
import { ToastrService } from 'ngx-toastr';
import { FormsModule } from '@angular/forms';
import { Subscription } from 'rxjs';

import { IOrder } from '../../../../core/models/order.model';
import { OrderService } from '../../../../core/services/order.service';
import { PUBLIC_ENDPOINTS } from '../../../../core/constants/urls';
import { CurrencyPipe } from '../../../../core/pipes/currency.pipe';

@Component({
  selector: 'app-order-detail',
  standalone: true,
  imports: [MatIconModule, CurrencyPipe, DatePipe, FormsModule],
  templateUrl: './order-detail.component.html',
  styleUrl: './order-detail.component.css'
})

export class OrderDetailComponent implements OnInit, OnDestroy {
  order!: IOrder;
  imageUrl = PUBLIC_ENDPOINTS.IMAGE_PRODUCTS;
  id!: string;
  status!: 'Confirmed' | 'Delivered' | 'Pending' | 'Cancelled';
  routeSub!: Subscription;

  private orderService = inject(OrderService);
  private activatedRoute = inject(ActivatedRoute);
  private toast = inject(ToastrService);

  ngOnInit(): void {
    this.routeSub = this.activatedRoute.params.subscribe(params => {
      if (params['id']) {
        this.getOrderById(params['id']);
      }
    });
  }

  getOrderById(id: string) {
    this.orderService.getOrderById(id).subscribe({
      next: (res) => {
        this.order = res.data;
        this.status = this.order.status;
      }
    });
  }

  onChangePaid(id: string) {
    this.orderService.updateOrder(id, { paymentInfo: { ...this.order.paymentInfo, isPaid: true } }).subscribe({
      next: (res) => {
        this.toast.success('This order is set to paid');
        this.getOrderById(id);
      },
      error: (err) => {
        console.error(err);
        this.toast.error("Failed to set paid.");
      }
    });
  }

  onChangeStatus(event: Event, id: string) {
    const target = event.target as HTMLSelectElement;
    this.orderService.updateOrder(id, { status: target.value }).subscribe({
      next: (res) => {
        this.toast.success('This order status is updated');
        this.getOrderById(id);
      },
      error: (err) => {
        console.error(err);
        this.toast.error("Failed to set status.");
      }
    });
  }

  ngOnDestroy(): void {
    this.routeSub.unsubscribe();
  }
}

<div class="container mx-auto h-full">
    <div class="mb-6">
        <div class="flex items-center mb-2">
            <h3 class="font-semibold text-2xl">
                <span>Order </span>
                <span class="ltr:ml-2 rtl:mr-2">#{{order.invoiceNo}}</span>
            </h3>
            <select class="py-2 px-1 border w-[160px] rounded-md cursor-pointer ms-8 border-primary-600" name="status"
                id="status" (change)="onChangeStatus($event, order._id)">
                @if(order.status === 'Cancelled') {
                <option value="Cancelled" [selected]="status === 'Cancelled'">Cancelled</option>
                }
                @if(order.status !== 'Cancelled') {
                @if(order.status !== 'Delivered') {
                @if(order.status !== 'Confirmed') {
                <option value="Pending" [selected]="status === 'Pending'">Pending</option>
                }
                <option value="Confirmed" [selected]="status === 'Confirmed'">Confirmed</option>
                }
                @if(order.status === 'Confirmed' || order.status === 'Delivered') {
                <option value="Delivered" [selected]="status === 'Delivered'">Delivered</option>
                }
                }
            </select>
        </div>
        <span class="flex items-center">
            <mat-icon>
                <span class="material-symbols-outlined">
                    date_range
                </span>
            </mat-icon>
            <span class="ms-2 rtl:mr-1">{{order.createdAt | date: 'dd/MM/yyy hh:mm a'}}</span>
        </span>
    </div>
    <div class="xl:flex gap-6">
        <div class="w-full">
            <div class="mb-4 border-0 card-border" role="presentation">
                <div>
                    <div class="overflow-x-auto">
                        <table class="w-full text-start">
                            <thead>
                                <tr>
                                    <th colspan="1">Product</th>
                                    <th colspan="1">Price</th>
                                    <th colspan="1">Quantity</th>
                                    <th colspan="1">Total</th>
                                </tr>
                            </thead>
                            <tbody>
                                @for(item of order.orderItems; track item.product.name) {
                                <tr>
                                    <td>
                                        <div class="flex items-center gap-3">
                                            <span class="avatar avatar-rounded"
                                                style="width: 50px; height: 50px; min-width: 50px; line-height: 50px; font-size: 12px;">
                                                <img class="avatar-img avatar-rounded"
                                                    [src]="imageUrl + '/' + item.product.images[0]" loading="lazy">
                                            </span>
                                            <div class="ltr:ml-2 rtl:mr-2">
                                                <h6>{{item.product.name}}</h6>
                                            </div>
                                        </div>
                                    </td>
                                    <td><span>{{item.product.price | currency}}</span></td>
                                    <td>{{item.quantity}}</td>
                                    <td><span>{{(item.product.price * item.quantity) | currency}}</span></td>
                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="xl:max-w-[360px] w-full">
            <div class="card card-border" role="presentation">
                <div class="card-body">
                    <h5 class="mb-2 text-2xl font-semibold">Customer</h5>
                    <span class="group flex items-center justify-between">
                        <div class="flex items-center">
                            <div class="ltr:ml-2 rtl:mr-2">
                                <div class="font-semibold">
                                    Full Name: {{order.customerInfo.firstName + ' ' + order.customerInfo.lastName}}
                                </div>
                                <span>
                                    <span class="font-semibold">11 </span>previous orders
                                </span>
                            </div>
                        </div>
                    </span>
                    <hr class="my-5">
                    <span class="flex text-gray-500 items-center gap-2 mb-4">
                        <mat-icon>
                            <span class="material-symbols-outlined">
                                mail
                            </span>
                        </mat-icon>
                        <span class="font-semibold">{{order.customerInfo.email}}</span>
                    </span>
                    <span class="flex text-gray-500 items-center gap-2">
                        <mat-icon>
                            <span class="material-symbols-outlined">
                                call
                            </span>
                        </mat-icon>
                        <span class="font-semibold">{{order.customerInfo.phone}}</span>
                    </span>
                    <hr class="my-5">
                    <h6 class="mb-4 flex items-center gap-2 text-gray-500">
                        <mat-icon>
                            <span class="material-symbols-outlined">
                                location_on
                            </span>
                        </mat-icon>
                        <span>Shipping Address</span>
                    </h6>
                    <address class="not-italic text-gray-500">
                        <div class="mb-1">Zip Code: {{order.shippingInfo.zipCode}}</div>
                        <div class="mb-1">Street: {{order.shippingInfo.address}}</div>
                        <div class="mb-1">City: {{order.shippingInfo.city}}</div>
                        <div>Country: {{order.shippingInfo.country}}</div>
                    </address>
                    <div class="mt-4 pb-20" role="presentation">
                        <div class="card-body">
                            <h5 class="mb-2 text-2xl font-semibold">Payment Summary</h5>
                            <ul class="text-gray-500">
                                <li class="flex items-center justify-between mb-3">
                                    <span>Discount: </span>
                                    <span class="font-semibold">
                                        <span>{{order.discount | currency}}</span>
                                    </span>
                                </li>
                                <li class="flex items-center justify-between mb-3">
                                    <span>Delivery fee: </span>
                                    <span class="font-semibold">
                                        <span>{{order.shippingInfo.cost! | currency}}</span>
                                    </span>
                                </li>
                                <li class="flex items-center justify-between">
                                    <span>Total: </span>
                                    <span class="font-semibold">
                                        <span>{{(order.totalPrice + order.shippingInfo.cost!) | currency}}</span>
                                    </span>
                                </li>
                            </ul>
                        </div>
                        <div class="mt-2 text-center w-full">
                            @if(order.paymentInfo.isPaid) {
                            <span
                                class="py-2 transition-all block text-white font-semibold w-full bg-red-600 rounded-lg">This
                                order is paid.</span>
                            }
                            @else {
                            <button (click)="onChangePaid(order._id)"
                                class="py-2 hover:bg-primary-700 transition-all text-white font-semibold w-full bg-primary-600 rounded-lg">
                                Paid ?
                            </button>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
